In [46]:
import pandas as pd

In [47]:
df = pd.read_excel("three_phase_IM_random_dataset.xlsx")
df.head()

,Torque_Nm,Flux_Wb,Angle_deg,Sector,Pulse_A_Upper,Pulse_B_Upper,Pulse_C_Upper,Pulse_A_Lower,Pulse_B_Lower,Pulse_C_Lower
0,20.867,1.046,211.048,4,0,1,0,1,1,0
1,26.941,0.638,132.754,3,0,1,0,1,0,1
2,0.745,0.723,224.578,4,0,1,0,1,1,0
3,1.956,0.161,154.833,3,0,1,0,1,0,1
4,0.522,0.269,299.427,5,0,1,1,0,1,0

In [48]:
df1 = df.drop(["Angle_deg"] , axis = 1)
df1.head()

,Torque_Nm,Flux_Wb,Sector,Pulse_A_Upper,Pulse_B_Upper,Pulse_C_Upper,Pulse_A_Lower,Pulse_B_Lower,Pulse_C_Lower
0,20.867,1.046,4,0,1,0,1,1,0
1,26.941,0.638,3,0,1,0,1,0,1
2,0.745,0.723,4,0,1,0,1,1,0
3,1.956,0.161,3,0,1,0,1,0,1
4,0.522,0.269,5,0,1,1,0,1,0

In [49]:
df2 = df.drop(["Sector"] , axis = 1)
df2.head()

,Torque_Nm,Flux_Wb,Angle_deg,Pulse_A_Upper,Pulse_B_Upper,Pulse_C_Upper,Pulse_A_Lower,Pulse_B_Lower,Pulse_C_Lower
0,20.867,1.046,211.048,0,1,0,1,1,0
1,26.941,0.638,132.754,0,1,0,1,0,1
2,0.745,0.723,224.578,0,1,0,1,1,0
3,1.956,0.161,154.833,0,1,0,1,0,1
4,0.522,0.269,299.427,0,1,1,0,1,0

## df1 we removed angle and in df2 we removed sector

## working with df1

In [50]:
import torch

In [51]:
import torch.nn as nn

In [52]:
class MotorModel_1(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = nn.Linear(4 , 64)
        self.l2 = nn.Linear(64 , 128)
        self.l3 = nn.Linear(128 , 64)
        self.l4 = nn.Linear(64 , 6)
        self.r = nn.ReLU()
        self.d = nn.Dropout(0.15)
    def forward(self , x):
        return self.l4(self.d(self.r(self.l3(self.d(self.r(self.l2(self.d(self.r(self.l1(x))))))))))

In [53]:
df1.dtypes

Torque_Nm        float64
Flux_Wb          float64
Sector             int64
Pulse_A_Upper      int64
Pulse_B_Upper      int64
Pulse_C_Upper      int64
Pulse_A_Lower      int64
Pulse_B_Lower      int64
Pulse_C_Lower      int64
dtype: object

In [54]:
df1.head()

,Torque_Nm,Flux_Wb,Sector,Pulse_A_Upper,Pulse_B_Upper,Pulse_C_Upper,Pulse_A_Lower,Pulse_B_Lower,Pulse_C_Lower
0,20.867,1.046,4,0,1,0,1,1,0
1,26.941,0.638,3,0,1,0,1,0,1
2,0.745,0.723,4,0,1,0,1,1,0
3,1.956,0.161,3,0,1,0,1,0,1
4,0.522,0.269,5,0,1,1,0,1,0

In [55]:
x1 = df1.drop(["Pulse_A_Upper"	, "Pulse_B_Upper" , "Pulse_C_Upper" ,	"Pulse_A_Lower" ,	"Pulse_B_Lower" ,	"Pulse_C_Lower"] , axis = 1)
x1.head()

   Torque_Nm  Flux_Wb  Sector
0     20.867    1.046       4
1     26.941    0.638       3
2      0.745    0.723       4
3      1.956    0.161       3
4      0.522    0.269       5

In [56]:
y1 =  df1.drop(["Torque_Nm"	, "Flux_Wb" ,	"Sector"] , axis = 1)
y1.head()

,Pulse_A_Upper,Pulse_B_Upper,Pulse_C_Upper,Pulse_A_Lower,Pulse_B_Lower,Pulse_C_Lower
0,0,1,0,1,1,0
1,0,1,0,1,0,1
2,0,1,0,1,1,0
3,0,1,0,1,0,1
4,0,1,1,0,1,0

In [57]:
import numpy as np
x1["Sector_sin"] = np.sin(2 * np.pi * df["Sector"] / 6)
x1["Sector_cos"] = np.cos(2 * np.pi * df["Sector"] / 6)

In [58]:
x1.head()

   Torque_Nm  Flux_Wb  Sector    Sector_sin  Sector_cos
0     20.867    1.046       4 -8.660254e-01        -0.5
1     26.941    0.638       3  1.224647e-16        -1.0
2      0.745    0.723       4 -8.660254e-01        -0.5
3      1.956    0.161       3  1.224647e-16        -1.0
4      0.522    0.269       5 -8.660254e-01         0.5

In [59]:
x1 = x1.drop(["Sector"], axis=1)
x1.head()

   Torque_Nm  Flux_Wb    Sector_sin  Sector_cos
0     20.867    1.046 -8.660254e-01        -0.5
1     26.941    0.638  1.224647e-16        -1.0
2      0.745    0.723 -8.660254e-01        -0.5
3      1.956    0.161  1.224647e-16        -1.0
4      0.522    0.269 -8.660254e-01         0.5

In [60]:
x1["Torque_Nm"].value_counts()

Torque_Nm
36.951    2
47.257    2
2.045     2
32.901    2
14.745    2
         ..
30.124    1
35.923    1
14.574    1
7.068     1
45.171    1
Name: count, Length: 988, dtype: int64

In [61]:
from sklearn.model_selection import train_test_split
x1_train , x1_test , y1_train , y1_test = train_test_split(x1 , y1 , random_state = 19 , test_size = 0.3)

In [62]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x1_train = scaler.fit_transform(x1_train)

x1_test = scaler.transform(x1_test)

In [63]:
x1_train = torch.tensor(x1_train, dtype=torch.float32)
x1_test = torch.tensor(x1_test, dtype=torch.float32)
y1_train = torch.tensor(y1_train.values, dtype=torch.float32)
y1_test = torch.tensor(y1_test.values, dtype=torch.float32)

In [64]:
x1_train

tensor([[-1.2235,  0.5334, -1.3194, -0.6470],
        [ 1.0705, -1.0283,  1.1734, -0.6470],
        [-1.5120,  1.5880, -1.3194, -0.6470],
        ...,
        [-0.1250,  0.0107,  1.1734,  0.7487],
        [-0.9330,  0.6796,  1.1734, -0.6470],
        [-1.1875, -0.7701, -1.3194, -0.6470]])

In [65]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [66]:
m1 = MotorModel_1().to(device)

In [67]:
loss = nn.BCEWithLogitsLoss()

In [68]:
import torch.optim as optim
optimizer = optim.Adam(m1.parameters() , lr = 0.001)

In [69]:
!pip install tqdm

Requirement already satisfied: tqdm in C:\Users\divyadarshee dash\.conda\envs\Dash\Lib\site-packages (4.68.1)
Requirement already satisfied: colorama in C:\Users\divyadarshee dash\.conda\envs\Dash\Lib\site-packages (from tqdm) (0.4.6)

In [70]:
def train_step(model , epoch , Acc , loss , optimizer , x1_train , y1_train , x1_test , y1_test):
    model = model.to(device)
    x1_train , y1_train , x1_test , y1_test = x1_train.to(device) , y1_train.to(device) , x1_test.to(device) , y1_test.to(device)
    loss = loss.to(device)
    from tqdm.auto import tqdm
    for i in tqdm(range(epoch)):
        model.train()
        y_pred = model(x1_train)
        train_loss = loss(y_pred, y1_train)
        optimizer.zero_grad()
        train_loss.backward()
        optimizer.step()

        
        model.eval()
        with torch.inference_mode():
            test_pred = model(x1_test)
            test_loss = loss(test_pred, y1_test)
            pred_labels = (
                torch.sigmoid(test_pred) > 0.5
            ).float()
            acc = Acc(pred_labels, y1_test)

        if i % 2 == 0:

            print(f"""Epoch : {i}  Train Loss : {train_loss:.4f}  Test Loss : {test_loss:.4f}  Accuracy : {acc:.4f} """)

In [71]:
from torchmetrics.classification import MultilabelAccuracy
acc = MultilabelAccuracy(num_labels = 6).to(device)

In [72]:
!pip install torchmetrics

Requirement already satisfied: torchmetrics in C:\Users\divyadarshee dash\.conda\envs\Dash\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>1.20.0 in C:\Users\divyadarshee dash\.conda\envs\Dash\Lib\site-packages (from torchmetrics) (2.4.6)
Requirement already satisfied: packaging>17.1 in C:\Users\divyadarshee dash\.conda\envs\Dash\Lib\site-packages (from torchmetrics) (26.0)
Requirement already satisfied: torch>=2.0.0 in C:\Users\divyadarshee dash\.conda\envs\Dash\Lib\site-packages (from torchmetrics) (2.11.0+cu128)
Requirement already satisfied: lightning-utilities>=0.15.3 in C:\Users\divyadarshee dash\.conda\envs\Dash\Lib\site-packages (from torchmetrics) (0.15.3)
Requirement already satisfied: typing_extensions in C:\Users\divyadarshee dash\.conda\envs\Dash\Lib\site-packages (from lightning-utilities>=0.15.3->torchmetrics) (4.15.0)
Requirement already satisfied: filelock in C:\Users\divyadarshee dash\.conda\envs\Dash\Lib\site-packages (from torch>=2.0.0->torchmetrics) (3.29.1)
Requirement already satisfied: setuptools<82 in C:\Users\divyadarshee dash\.conda\envs\Dash\Lib\site-packages (from torch>=2.0.0->torchmetrics) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in C:\Users\divyadarshee dash\.conda\envs\Dash\Lib\site-packages (from torch>=2.0.0->torchmetrics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in C:\Users\divyadarshee dash\.conda\envs\Dash\Lib\site-packages (from torch>=2.0.0->torchmetrics) (3.6.1)
Requirement already satisfied: jinja2 in C:\Users\divyadarshee dash\.conda\envs\Dash\Lib\site-packages (from torch>=2.0.0->torchmetrics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in C:\Users\divyadarshee dash\.conda\envs\Dash\Lib\site-packages (from torch>=2.0.0->torchmetrics) (2026.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in C:\Users\divyadarshee dash\.conda\envs\Dash\Lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->torchmetrics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\divyadarshee dash\.conda\envs\Dash\Lib\site-packages (from jinja2->torch>=2.0.0->torchmetrics) (3.0.2)

In [73]:
train_step(m1 ,100 , acc , loss , optimizer , x1_train , y1_train , x1_test , y1_test)

  0%|          | 0/100 [00:00<?, ?it/s]

Epoch : 0  Train Loss : 0.6965  Test Loss : 0.6910  Accuracy : 0.4994
Epoch : 2  Train Loss : 0.6878  Test Loss : 0.6829  Accuracy : 0.5594
Epoch : 4  Train Loss : 0.6805  Test Loss : 0.6744  Accuracy : 0.6000
Epoch : 6  Train Loss : 0.6716  Test Loss : 0.6651  Accuracy : 0.6906
Epoch : 8  Train Loss : 0.6623  Test Loss : 0.6543  Accuracy : 0.7972
Epoch : 10  Train Loss : 0.6504  Test Loss : 0.6414  Accuracy : 0.8261
Epoch : 12  Train Loss : 0.6373  Test Loss : 0.6258  Accuracy : 0.8456
Epoch : 14  Train Loss : 0.6209  Test Loss : 0.6071  Accuracy : 0.8628
Epoch : 16  Train Loss : 0.6006  Test Loss : 0.5848  Accuracy : 0.8794
Epoch : 18  Train Loss : 0.5769  Test Loss : 0.5586  Accuracy : 0.9078
Epoch : 20  Train Loss : 0.5487  Test Loss : 0.5283  Accuracy : 0.9333
Epoch : 22  Train Loss : 0.5197  Test Loss : 0.4940  Accuracy : 0.9506
Epoch : 24  Train Loss : 0.4829  Test Loss : 0.4560  Accuracy : 0.9639
Epoch : 26  Train Loss : 0.4441  Test Loss : 0.4149  Accuracy : 0.9656
Epoch : 28  Train Loss : 0.4047  Test Loss : 0.3719  Accuracy : 0.9744
Epoch : 30  Train Loss : 0.3626  Test Loss : 0.3279  Accuracy : 0.9822
Epoch : 32  Train Loss : 0.3192  Test Loss : 0.2841  Accuracy : 0.9894
Epoch : 34  Train Loss : 0.2792  Test Loss : 0.2419  Accuracy : 0.9956
Epoch : 36  Train Loss : 0.2403  Test Loss : 0.2022  Accuracy : 0.9994
Epoch : 38  Train Loss : 0.2031  Test Loss : 0.1661  Accuracy : 1.0000
Epoch : 40  Train Loss : 0.1649  Test Loss : 0.1342  Accuracy : 1.0000
Epoch : 42  Train Loss : 0.1427  Test Loss : 0.1069  Accuracy : 1.0000
Epoch : 44  Train Loss : 0.1173  Test Loss : 0.0841  Accuracy : 1.0000
Epoch : 46  Train Loss : 0.0938  Test Loss : 0.0656  Accuracy : 1.0000
Epoch : 48  Train Loss : 0.0759  Test Loss : 0.0509  Accuracy : 1.0000
Epoch : 50  Train Loss : 0.0654  Test Loss : 0.0395  Accuracy : 1.0000
Epoch : 52  Train Loss : 0.0571  Test Loss : 0.0308  Accuracy : 1.0000
Epoch : 54  Train Loss : 0.0446  Test Loss : 0.0241  Accuracy : 1.0000
Epoch : 56  Train Loss : 0.0378  Test Loss : 0.0191  Accuracy : 1.0000
Epoch : 58  Train Loss : 0.0348  Test Loss : 0.0153  Accuracy : 1.0000
Epoch : 60  Train Loss : 0.0263  Test Loss : 0.0124  Accuracy : 1.0000
Epoch : 62  Train Loss : 0.0261  Test Loss : 0.0101  Accuracy : 1.0000
Epoch : 64  Train Loss : 0.0209  Test Loss : 0.0084  Accuracy : 1.0000
Epoch : 66  Train Loss : 0.0198  Test Loss : 0.0070  Accuracy : 1.0000
Epoch : 68  Train Loss : 0.0170  Test Loss : 0.0060  Accuracy : 1.0000
Epoch : 70  Train Loss : 0.0155  Test Loss : 0.0051  Accuracy : 1.0000
Epoch : 72  Train Loss : 0.0138  Test Loss : 0.0044  Accuracy : 1.0000
Epoch : 74  Train Loss : 0.0127  Test Loss : 0.0039  Accuracy : 1.0000
Epoch : 76  Train Loss : 0.0125  Test Loss : 0.0034  Accuracy : 1.0000
Epoch : 78  Train Loss : 0.0123  Test Loss : 0.0030  Accuracy : 1.0000
Epoch : 80  Train Loss : 0.0104  Test Loss : 0.0027  Accuracy : 1.0000
Epoch : 82  Train Loss : 0.0102  Test Loss : 0.0024  Accuracy : 1.0000
Epoch : 84  Train Loss : 0.0087  Test Loss : 0.0022  Accuracy : 1.0000
Epoch : 86  Train Loss : 0.0088  Test Loss : 0.0020  Accuracy : 1.0000
Epoch : 88  Train Loss : 0.0074  Test Loss : 0.0018  Accuracy : 1.0000
Epoch : 90  Train Loss : 0.0076  Test Loss : 0.0017  Accuracy : 1.0000
Epoch : 92  Train Loss : 0.0078  Test Loss : 0.0015  Accuracy : 1.0000
Epoch : 94  Train Loss : 0.0093  Test Loss : 0.0014  Accuracy : 1.0000
Epoch : 96  Train Loss : 0.0074  Test Loss : 0.0013  Accuracy : 1.0000
Epoch : 98  Train Loss : 0.0060  Test Loss : 0.0012  Accuracy : 1.0000

In [76]:

class ResidualBlock(nn.Module):

    def __init__(self, features):

        super().__init__()

        self.layer = nn.Sequential(

            nn.Linear(features, features),
            nn.ReLU(),

            nn.Linear(features, features)

        )

        self.relu = nn.ReLU()

    def forward(self, x):

        identity = x

        out = self.layer(x)

        out = out + identity

        out = self.relu(out)

        return out

In [77]:
class DeepResNet(nn.Module):

    def __init__(self):

        super().__init__()

        self.input = nn.Linear(4, 64)

        self.block1 = ResidualBlock(64)

        self.block2 = ResidualBlock(64)

        self.output = nn.Linear(64, 6)

        self.relu = nn.ReLU()

    def forward(self, x):

        x = self.relu(self.input(x))

        x = self.block1(x)

        x = self.block2(x)

        x = self.output(x)

        return x

In [78]:
m2 = DeepResNet().to(device)

In [79]:
op = optim.Adam(m2.parameters() , lr = 0.001)

In [80]:
train_step(m2 ,100 , acc , loss , op , x1_train , y1_train , x1_test , y1_test)

  0%|          | 0/100 [00:00<?, ?it/s]

Epoch : 0  Train Loss : 0.7081  Test Loss : 0.6937  Accuracy : 0.5478
Epoch : 2  Train Loss : 0.6863  Test Loss : 0.6723  Accuracy : 0.6033
Epoch : 4  Train Loss : 0.6654  Test Loss : 0.6514  Accuracy : 0.6661
Epoch : 6  Train Loss : 0.6448  Test Loss : 0.6306  Accuracy : 0.7044
Epoch : 8  Train Loss : 0.6239  Test Loss : 0.6092  Accuracy : 0.7433
Epoch : 10  Train Loss : 0.6021  Test Loss : 0.5867  Accuracy : 0.7961
Epoch : 12  Train Loss : 0.5791  Test Loss : 0.5627  Accuracy : 0.8422
Epoch : 14  Train Loss : 0.5543  Test Loss : 0.5368  Accuracy : 0.8756
Epoch : 16  Train Loss : 0.5273  Test Loss : 0.5085  Accuracy : 0.8950
Epoch : 18  Train Loss : 0.4976  Test Loss : 0.4775  Accuracy : 0.9228
Epoch : 20  Train Loss : 0.4648  Test Loss : 0.4434  Accuracy : 0.9439
Epoch : 22  Train Loss : 0.4289  Test Loss : 0.4063  Accuracy : 0.9656
Epoch : 24  Train Loss : 0.3900  Test Loss : 0.3666  Accuracy : 0.9772
Epoch : 26  Train Loss : 0.3485  Test Loss : 0.3245  Accuracy : 0.9833
Epoch : 28  Train Loss : 0.3049  Test Loss : 0.2808  Accuracy : 0.9900
Epoch : 30  Train Loss : 0.2601  Test Loss : 0.2365  Accuracy : 0.9950
Epoch : 32  Train Loss : 0.2152  Test Loss : 0.1932  Accuracy : 0.9994
Epoch : 34  Train Loss : 0.1721  Test Loss : 0.1526  Accuracy : 1.0000
Epoch : 36  Train Loss : 0.1325  Test Loss : 0.1162  Accuracy : 1.0000
Epoch : 38  Train Loss : 0.0982  Test Loss : 0.0854  Accuracy : 1.0000
Epoch : 40  Train Loss : 0.0702  Test Loss : 0.0608  Accuracy : 1.0000
Epoch : 42  Train Loss : 0.0486  Test Loss : 0.0421  Accuracy : 1.0000
Epoch : 44  Train Loss : 0.0329  Test Loss : 0.0286  Accuracy : 1.0000
Epoch : 46  Train Loss : 0.0219  Test Loss : 0.0191  Accuracy : 1.0000
Epoch : 48  Train Loss : 0.0145  Test Loss : 0.0127  Accuracy : 1.0000
Epoch : 50  Train Loss : 0.0096  Test Loss : 0.0086  Accuracy : 1.0000
Epoch : 52  Train Loss : 0.0065  Test Loss : 0.0059  Accuracy : 1.0000
Epoch : 54  Train Loss : 0.0045  Test Loss : 0.0041  Accuracy : 1.0000
Epoch : 56  Train Loss : 0.0032  Test Loss : 0.0030  Accuracy : 1.0000
Epoch : 58  Train Loss : 0.0023  Test Loss : 0.0022  Accuracy : 1.0000
Epoch : 60  Train Loss : 0.0018  Test Loss : 0.0017  Accuracy : 1.0000
Epoch : 62  Train Loss : 0.0014  Test Loss : 0.0013  Accuracy : 1.0000
Epoch : 64  Train Loss : 0.0011  Test Loss : 0.0011  Accuracy : 1.0000
Epoch : 66  Train Loss : 0.0009  Test Loss : 0.0009  Accuracy : 1.0000
Epoch : 68  Train Loss : 0.0008  Test Loss : 0.0008  Accuracy : 1.0000
Epoch : 70  Train Loss : 0.0006  Test Loss : 0.0007  Accuracy : 1.0000
Epoch : 72  Train Loss : 0.0006  Test Loss : 0.0006  Accuracy : 1.0000
Epoch : 74  Train Loss : 0.0005  Test Loss : 0.0005  Accuracy : 1.0000
Epoch : 76  Train Loss : 0.0005  Test Loss : 0.0005  Accuracy : 1.0000
Epoch : 78  Train Loss : 0.0004  Test Loss : 0.0004  Accuracy : 1.0000
Epoch : 80  Train Loss : 0.0004  Test Loss : 0.0004  Accuracy : 1.0000
Epoch : 82  Train Loss : 0.0004  Test Loss : 0.0004  Accuracy : 1.0000
Epoch : 84  Train Loss : 0.0003  Test Loss : 0.0004  Accuracy : 1.0000
Epoch : 86  Train Loss : 0.0003  Test Loss : 0.0003  Accuracy : 1.0000
Epoch : 88  Train Loss : 0.0003  Test Loss : 0.0003  Accuracy : 1.0000
Epoch : 90  Train Loss : 0.0003  Test Loss : 0.0003  Accuracy : 1.0000
Epoch : 92  Train Loss : 0.0003  Test Loss : 0.0003  Accuracy : 1.0000
Epoch : 94  Train Loss : 0.0003  Test Loss : 0.0003  Accuracy : 1.0000
Epoch : 96  Train Loss : 0.0003  Test Loss : 0.0003  Accuracy : 1.0000
Epoch : 98  Train Loss : 0.0002  Test Loss : 0.0003  Accuracy : 1.0000

In [81]:
!pip install lightgbm

Requirement already satisfied: lightgbm in C:\Users\divyadarshee dash\.conda\envs\Dash\Lib\site-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in C:\Users\divyadarshee dash\.conda\envs\Dash\Lib\site-packages (from lightgbm) (2.4.6)
Requirement already satisfied: scipy in C:\Users\divyadarshee dash\.conda\envs\Dash\Lib\site-packages (from lightgbm) (1.17.1)

In [82]:
import torch
from torch import nn

class MLP(nn.Module):
    
    def __init__(self):
        super().__init__()
        
        self.layer_stack = nn.Sequential(
            
            nn.Linear(4, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            
            nn.Linear(64, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            
            nn.Linear(64, 6)
        )
        
    def forward(self, x):
        
        return self.layer_stack(x)


m1 = MLP()

In [83]:
op1 = optim.Adam(m1.parameters() , lr = 0.001)

In [84]:
train_step(m1 ,100 , acc , loss , op1 , x1_train , y1_train , x1_test , y1_test)

  0%|          | 0/100 [00:00<?, ?it/s]

Epoch : 0  Train Loss : 0.7011  Test Loss : 0.6981  Accuracy : 0.4944
Epoch : 2  Train Loss : 0.6926  Test Loss : 0.6894  Accuracy : 0.5228
Epoch : 4  Train Loss : 0.6831  Test Loss : 0.6804  Accuracy : 0.5589
Epoch : 6  Train Loss : 0.6756  Test Loss : 0.6712  Accuracy : 0.6083
Epoch : 8  Train Loss : 0.6653  Test Loss : 0.6616  Accuracy : 0.6689
Epoch : 10  Train Loss : 0.6569  Test Loss : 0.6514  Accuracy : 0.7189
Epoch : 12  Train Loss : 0.6446  Test Loss : 0.6407  Accuracy : 0.7661
Epoch : 14  Train Loss : 0.6346  Test Loss : 0.6292  Accuracy : 0.8061
Epoch : 16  Train Loss : 0.6235  Test Loss : 0.6169  Accuracy : 0.8400
Epoch : 18  Train Loss : 0.6112  Test Loss : 0.6036  Accuracy : 0.8744
Epoch : 20  Train Loss : 0.5977  Test Loss : 0.5893  Accuracy : 0.8961
Epoch : 22  Train Loss : 0.5852  Test Loss : 0.5740  Accuracy : 0.9094
Epoch : 24  Train Loss : 0.5692  Test Loss : 0.5577  Accuracy : 0.9211
Epoch : 26  Train Loss : 0.5522  Test Loss : 0.5405  Accuracy : 0.9378
Epoch : 28  Train Loss : 0.5353  Test Loss : 0.5223  Accuracy : 0.9506
Epoch : 30  Train Loss : 0.5165  Test Loss : 0.5033  Accuracy : 0.9567
Epoch : 32  Train Loss : 0.4982  Test Loss : 0.4836  Accuracy : 0.9628
Epoch : 34  Train Loss : 0.4781  Test Loss : 0.4633  Accuracy : 0.9694
Epoch : 36  Train Loss : 0.4611  Test Loss : 0.4424  Accuracy : 0.9717
Epoch : 38  Train Loss : 0.4438  Test Loss : 0.4212  Accuracy : 0.9750
Epoch : 40  Train Loss : 0.4212  Test Loss : 0.3997  Accuracy : 0.9783
Epoch : 42  Train Loss : 0.3997  Test Loss : 0.3780  Accuracy : 0.9828
Epoch : 44  Train Loss : 0.3766  Test Loss : 0.3564  Accuracy : 0.9878
Epoch : 46  Train Loss : 0.3584  Test Loss : 0.3350  Accuracy : 0.9939
Epoch : 48  Train Loss : 0.3368  Test Loss : 0.3139  Accuracy : 0.9939
Epoch : 50  Train Loss : 0.3153  Test Loss : 0.2933  Accuracy : 0.9972
Epoch : 52  Train Loss : 0.2973  Test Loss : 0.2733  Accuracy : 0.9989
Epoch : 54  Train Loss : 0.2761  Test Loss : 0.2541  Accuracy : 0.9994
Epoch : 56  Train Loss : 0.2609  Test Loss : 0.2356  Accuracy : 1.0000
Epoch : 58  Train Loss : 0.2445  Test Loss : 0.2181  Accuracy : 1.0000
Epoch : 60  Train Loss : 0.2253  Test Loss : 0.2015  Accuracy : 1.0000
Epoch : 62  Train Loss : 0.2106  Test Loss : 0.1859  Accuracy : 1.0000
Epoch : 64  Train Loss : 0.1937  Test Loss : 0.1713  Accuracy : 1.0000
Epoch : 66  Train Loss : 0.1791  Test Loss : 0.1577  Accuracy : 1.0000
Epoch : 68  Train Loss : 0.1669  Test Loss : 0.1451  Accuracy : 1.0000
Epoch : 70  Train Loss : 0.1557  Test Loss : 0.1335  Accuracy : 1.0000
Epoch : 72  Train Loss : 0.1472  Test Loss : 0.1228  Accuracy : 1.0000
Epoch : 74  Train Loss : 0.1346  Test Loss : 0.1131  Accuracy : 1.0000
Epoch : 76  Train Loss : 0.1246  Test Loss : 0.1041  Accuracy : 1.0000
Epoch : 78  Train Loss : 0.1204  Test Loss : 0.0959  Accuracy : 1.0000
Epoch : 80  Train Loss : 0.1109  Test Loss : 0.0884  Accuracy : 1.0000
Epoch : 82  Train Loss : 0.1024  Test Loss : 0.0816  Accuracy : 1.0000
Epoch : 84  Train Loss : 0.0947  Test Loss : 0.0754  Accuracy : 1.0000
Epoch : 86  Train Loss : 0.0910  Test Loss : 0.0697  Accuracy : 1.0000
Epoch : 88  Train Loss : 0.0832  Test Loss : 0.0646  Accuracy : 1.0000
Epoch : 90  Train Loss : 0.0809  Test Loss : 0.0598  Accuracy : 1.0000
Epoch : 92  Train Loss : 0.0781  Test Loss : 0.0555  Accuracy : 1.0000
Epoch : 94  Train Loss : 0.0726  Test Loss : 0.0516  Accuracy : 1.0000
Epoch : 96  Train Loss : 0.0681  Test Loss : 0.0481  Accuracy : 1.0000
Epoch : 98  Train Loss : 0.0637  Test Loss : 0.0448  Accuracy : 1.0000

In [85]:
import torch
from torch import nn

class MotorANN(nn.Module):
    
    def __init__(self):
        
        super().__init__()
        
        self.network = nn.Sequential(
            
            nn.Linear(4, 50),
            nn.Sigmoid(),
            
            nn.Linear(50, 50),
            nn.Sigmoid(),
            
            nn.Linear(50, 6)
        )
        
    def forward(self, x):
        
        return self.network(x)


model = MotorANN()

In [86]:
optimizer = torch.optim.Adam(model.parameters(),lr=0.001)

In [87]:
train_step(model ,10 , acc , loss , optimizer , x1_train , y1_train , x1_test , y1_test)

  0%|          | 0/10 [00:00<?, ?it/s]

Epoch : 0  Train Loss : 0.7214  Test Loss : 0.7167  Accuracy : 0.5000
Epoch : 2  Train Loss : 0.7147  Test Loss : 0.7107  Accuracy : 0.5000
Epoch : 4  Train Loss : 0.7089  Test Loss : 0.7055  Accuracy : 0.5000
Epoch : 6  Train Loss : 0.7040  Test Loss : 0.7012  Accuracy : 0.5000
Epoch : 8  Train Loss : 0.6998  Test Loss : 0.6975  Accuracy : 0.5000

In [88]:
x1_train[0]

tensor([-1.2235,  0.5334, -1.3194, -0.6470])

In [89]:
import torch
from torch import nn

class ModernANN(nn.Module):
    
    def __init__(self):
        
        super().__init__()
        
        self.network = nn.Sequential(
            
            nn.Linear(4, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            
            nn.Linear(64, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            
            nn.Linear(64, 6)
        )
        
    def forward(self, x):
        
        return self.network(x)


modern_model = ModernANN()

In [90]:
modern_optimizer = torch.optim.Adam(
    modern_model.parameters(),
    lr=0.001,
    weight_decay=1e-4
)

In [91]:
train_step(modern_model ,500 , acc , loss , modern_optimizer , x1_train , y1_train , x1_test , y1_test)

  0%|          | 0/500 [00:00<?, ?it/s]

Epoch : 0  Train Loss : 0.6995  Test Loss : 0.6947  Accuracy : 0.5539
Epoch : 2  Train Loss : 0.6910  Test Loss : 0.6864  Accuracy : 0.5889
Epoch : 4  Train Loss : 0.6835  Test Loss : 0.6784  Accuracy : 0.6556
Epoch : 6  Train Loss : 0.6761  Test Loss : 0.6703  Accuracy : 0.6989
Epoch : 8  Train Loss : 0.6676  Test Loss : 0.6621  Accuracy : 0.7278
Epoch : 10  Train Loss : 0.6592  Test Loss : 0.6536  Accuracy : 0.7472
Epoch : 12  Train Loss : 0.6520  Test Loss : 0.6447  Accuracy : 0.7700
Epoch : 14  Train Loss : 0.6421  Test Loss : 0.6353  Accuracy : 0.7817
Epoch : 16  Train Loss : 0.6314  Test Loss : 0.6252  Accuracy : 0.7928
Epoch : 18  Train Loss : 0.6238  Test Loss : 0.6143  Accuracy : 0.7978
Epoch : 20  Train Loss : 0.6110  Test Loss : 0.6027  Accuracy : 0.8028
Epoch : 22  Train Loss : 0.5985  Test Loss : 0.5901  Accuracy : 0.8100
Epoch : 24  Train Loss : 0.5867  Test Loss : 0.5766  Accuracy : 0.8139
Epoch : 26  Train Loss : 0.5739  Test Loss : 0.5622  Accuracy : 0.8278
Epoch : 28  Train Loss : 0.5579  Test Loss : 0.5468  Accuracy : 0.8539
Epoch : 30  Train Loss : 0.5415  Test Loss : 0.5305  Accuracy : 0.8789
Epoch : 32  Train Loss : 0.5255  Test Loss : 0.5132  Accuracy : 0.8917
Epoch : 34  Train Loss : 0.5112  Test Loss : 0.4951  Accuracy : 0.9056
Epoch : 36  Train Loss : 0.4913  Test Loss : 0.4763  Accuracy : 0.9133
Epoch : 38  Train Loss : 0.4737  Test Loss : 0.4568  Accuracy : 0.9256
Epoch : 40  Train Loss : 0.4552  Test Loss : 0.4370  Accuracy : 0.9333
Epoch : 42  Train Loss : 0.4337  Test Loss : 0.4168  Accuracy : 0.9389
Epoch : 44  Train Loss : 0.4144  Test Loss : 0.3965  Accuracy : 0.9433
Epoch : 46  Train Loss : 0.3969  Test Loss : 0.3762  Accuracy : 0.9500
Epoch : 48  Train Loss : 0.3750  Test Loss : 0.3559  Accuracy : 0.9606
Epoch : 50  Train Loss : 0.3575  Test Loss : 0.3359  Accuracy : 0.9717
Epoch : 52  Train Loss : 0.3354  Test Loss : 0.3161  Accuracy : 0.9817
Epoch : 54  Train Loss : 0.3190  Test Loss : 0.2967  Accuracy : 0.9850
Epoch : 56  Train Loss : 0.3007  Test Loss : 0.2779  Accuracy : 0.9878
Epoch : 58  Train Loss : 0.2820  Test Loss : 0.2596  Accuracy : 0.9922
Epoch : 60  Train Loss : 0.2622  Test Loss : 0.2419  Accuracy : 0.9961
Epoch : 62  Train Loss : 0.2493  Test Loss : 0.2249  Accuracy : 0.9978
Epoch : 64  Train Loss : 0.2280  Test Loss : 0.2088  Accuracy : 0.9983
Epoch : 66  Train Loss : 0.2165  Test Loss : 0.1934  Accuracy : 1.0000
Epoch : 68  Train Loss : 0.1998  Test Loss : 0.1788  Accuracy : 1.0000
Epoch : 70  Train Loss : 0.1888  Test Loss : 0.1652  Accuracy : 1.0000
Epoch : 72  Train Loss : 0.1751  Test Loss : 0.1524  Accuracy : 1.0000
Epoch : 74  Train Loss : 0.1630  Test Loss : 0.1405  Accuracy : 1.0000
Epoch : 76  Train Loss : 0.1534  Test Loss : 0.1294  Accuracy : 1.0000
Epoch : 78  Train Loss : 0.1408  Test Loss : 0.1192  Accuracy : 1.0000
Epoch : 80  Train Loss : 0.1316  Test Loss : 0.1098  Accuracy : 1.0000
Epoch : 82  Train Loss : 0.1228  Test Loss : 0.1012  Accuracy : 1.0000
Epoch : 84  Train Loss : 0.1157  Test Loss : 0.0933  Accuracy : 1.0000
Epoch : 86  Train Loss : 0.1078  Test Loss : 0.0861  Accuracy : 1.0000
Epoch : 88  Train Loss : 0.0990  Test Loss : 0.0794  Accuracy : 1.0000
Epoch : 90  Train Loss : 0.0902  Test Loss : 0.0734  Accuracy : 1.0000
Epoch : 92  Train Loss : 0.0892  Test Loss : 0.0679  Accuracy : 1.0000
Epoch : 94  Train Loss : 0.0839  Test Loss : 0.0629  Accuracy : 1.0000
Epoch : 96  Train Loss : 0.0761  Test Loss : 0.0584  Accuracy : 1.0000
Epoch : 98  Train Loss : 0.0735  Test Loss : 0.0542  Accuracy : 1.0000
Epoch : 100  Train Loss : 0.0703  Test Loss : 0.0504  Accuracy : 1.0000
Epoch : 102  Train Loss : 0.0655  Test Loss : 0.0469  Accuracy : 1.0000
Epoch : 104  Train Loss : 0.0607  Test Loss : 0.0438  Accuracy : 1.0000
Epoch : 106  Train Loss : 0.0593  Test Loss : 0.0409  Accuracy : 1.0000
Epoch : 108  Train Loss : 0.0561  Test Loss : 0.0383  Accuracy : 1.0000
Epoch : 110  Train Loss : 0.0533  Test Loss : 0.0359  Accuracy : 1.0000
Epoch : 112  Train Loss : 0.0498  Test Loss : 0.0337  Accuracy : 1.0000
Epoch : 114  Train Loss : 0.0468  Test Loss : 0.0316  Accuracy : 1.0000
Epoch : 116  Train Loss : 0.0439  Test Loss : 0.0298  Accuracy : 1.0000
Epoch : 118  Train Loss : 0.0442  Test Loss : 0.0280  Accuracy : 1.0000
Epoch : 120  Train Loss : 0.0431  Test Loss : 0.0264  Accuracy : 1.0000
Epoch : 122  Train Loss : 0.0412  Test Loss : 0.0250  Accuracy : 1.0000
Epoch : 124  Train Loss : 0.0376  Test Loss : 0.0236  Accuracy : 1.0000
Epoch : 126  Train Loss : 0.0369  Test Loss : 0.0224  Accuracy : 1.0000
Epoch : 128  Train Loss : 0.0345  Test Loss : 0.0212  Accuracy : 1.0000
Epoch : 130  Train Loss : 0.0348  Test Loss : 0.0201  Accuracy : 1.0000
Epoch : 132  Train Loss : 0.0320  Test Loss : 0.0191  Accuracy : 1.0000
Epoch : 134  Train Loss : 0.0327  Test Loss : 0.0182  Accuracy : 1.0000
Epoch : 136  Train Loss : 0.0306  Test Loss : 0.0173  Accuracy : 1.0000
Epoch : 138  Train Loss : 0.0293  Test Loss : 0.0165  Accuracy : 1.0000
Epoch : 140  Train Loss : 0.0292  Test Loss : 0.0157  Accuracy : 1.0000
Epoch : 142  Train Loss : 0.0274  Test Loss : 0.0150  Accuracy : 1.0000
Epoch : 144  Train Loss : 0.0254  Test Loss : 0.0143  Accuracy : 1.0000
Epoch : 146  Train Loss : 0.0241  Test Loss : 0.0137  Accuracy : 1.0000
Epoch : 148  Train Loss : 0.0236  Test Loss : 0.0131  Accuracy : 1.0000
Epoch : 150  Train Loss : 0.0230  Test Loss : 0.0125  Accuracy : 1.0000
Epoch : 152  Train Loss : 0.0236  Test Loss : 0.0120  Accuracy : 1.0000
Epoch : 154  Train Loss : 0.0226  Test Loss : 0.0115  Accuracy : 1.0000
Epoch : 156  Train Loss : 0.0210  Test Loss : 0.0110  Accuracy : 1.0000
Epoch : 158  Train Loss : 0.0225  Test Loss : 0.0106  Accuracy : 1.0000
Epoch : 160  Train Loss : 0.0202  Test Loss : 0.0102  Accuracy : 1.0000
Epoch : 162  Train Loss : 0.0190  Test Loss : 0.0098  Accuracy : 1.0000
Epoch : 164  Train Loss : 0.0195  Test Loss : 0.0094  Accuracy : 1.0000
Epoch : 166  Train Loss : 0.0181  Test Loss : 0.0090  Accuracy : 1.0000
Epoch : 168  Train Loss : 0.0178  Test Loss : 0.0087  Accuracy : 1.0000
Epoch : 170  Train Loss : 0.0183  Test Loss : 0.0084  Accuracy : 1.0000
Epoch : 172  Train Loss : 0.0173  Test Loss : 0.0081  Accuracy : 1.0000
Epoch : 174  Train Loss : 0.0163  Test Loss : 0.0078  Accuracy : 1.0000
Epoch : 176  Train Loss : 0.0161  Test Loss : 0.0075  Accuracy : 1.0000
Epoch : 178  Train Loss : 0.0165  Test Loss : 0.0072  Accuracy : 1.0000
Epoch : 180  Train Loss : 0.0170  Test Loss : 0.0070  Accuracy : 1.0000
Epoch : 182  Train Loss : 0.0157  Test Loss : 0.0067  Accuracy : 1.0000
Epoch : 184  Train Loss : 0.0153  Test Loss : 0.0065  Accuracy : 1.0000
Epoch : 186  Train Loss : 0.0152  Test Loss : 0.0063  Accuracy : 1.0000
Epoch : 188  Train Loss : 0.0147  Test Loss : 0.0061  Accuracy : 1.0000
Epoch : 190  Train Loss : 0.0133  Test Loss : 0.0059  Accuracy : 1.0000
Epoch : 192  Train Loss : 0.0141  Test Loss : 0.0057  Accuracy : 1.0000
Epoch : 194  Train Loss : 0.0126  Test Loss : 0.0055  Accuracy : 1.0000
Epoch : 196  Train Loss : 0.0129  Test Loss : 0.0054  Accuracy : 1.0000
Epoch : 198  Train Loss : 0.0131  Test Loss : 0.0052  Accuracy : 1.0000
Epoch : 200  Train Loss : 0.0121  Test Loss : 0.0050  Accuracy : 1.0000
Epoch : 202  Train Loss : 0.0130  Test Loss : 0.0049  Accuracy : 1.0000
Epoch : 204  Train Loss : 0.0120  Test Loss : 0.0047  Accuracy : 1.0000
Epoch : 206  Train Loss : 0.0123  Test Loss : 0.0046  Accuracy : 1.0000
Epoch : 208  Train Loss : 0.0119  Test Loss : 0.0045  Accuracy : 1.0000
Epoch : 210  Train Loss : 0.0120  Test Loss : 0.0043  Accuracy : 1.0000
Epoch : 212  Train Loss : 0.0107  Test Loss : 0.0042  Accuracy : 1.0000
Epoch : 214  Train Loss : 0.0115  Test Loss : 0.0041  Accuracy : 1.0000
Epoch : 216  Train Loss : 0.0105  Test Loss : 0.0040  Accuracy : 1.0000
Epoch : 218  Train Loss : 0.0098  Test Loss : 0.0039  Accuracy : 1.0000
Epoch : 220  Train Loss : 0.0097  Test Loss : 0.0038  Accuracy : 1.0000
Epoch : 222  Train Loss : 0.0093  Test Loss : 0.0037  Accuracy : 1.0000
Epoch : 224  Train Loss : 0.0107  Test Loss : 0.0036  Accuracy : 1.0000
Epoch : 226  Train Loss : 0.0112  Test Loss : 0.0035  Accuracy : 1.0000
Epoch : 228  Train Loss : 0.0094  Test Loss : 0.0034  Accuracy : 1.0000
Epoch : 230  Train Loss : 0.0098  Test Loss : 0.0033  Accuracy : 1.0000
Epoch : 232  Train Loss : 0.0089  Test Loss : 0.0032  Accuracy : 1.0000
Epoch : 234  Train Loss : 0.0099  Test Loss : 0.0031  Accuracy : 1.0000
Epoch : 236  Train Loss : 0.0086  Test Loss : 0.0030  Accuracy : 1.0000
Epoch : 238  Train Loss : 0.0091  Test Loss : 0.0030  Accuracy : 1.0000
Epoch : 240  Train Loss : 0.0102  Test Loss : 0.0029  Accuracy : 1.0000
Epoch : 242  Train Loss : 0.0083  Test Loss : 0.0028  Accuracy : 1.0000
Epoch : 244  Train Loss : 0.0087  Test Loss : 0.0027  Accuracy : 1.0000
Epoch : 246  Train Loss : 0.0083  Test Loss : 0.0027  Accuracy : 1.0000
Epoch : 248  Train Loss : 0.0083  Test Loss : 0.0026  Accuracy : 1.0000
Epoch : 250  Train Loss : 0.0071  Test Loss : 0.0025  Accuracy : 1.0000
Epoch : 252  Train Loss : 0.0076  Test Loss : 0.0025  Accuracy : 1.0000
Epoch : 254  Train Loss : 0.0069  Test Loss : 0.0024  Accuracy : 1.0000
Epoch : 256  Train Loss : 0.0074  Test Loss : 0.0024  Accuracy : 1.0000
Epoch : 258  Train Loss : 0.0068  Test Loss : 0.0023  Accuracy : 1.0000
Epoch : 260  Train Loss : 0.0072  Test Loss : 0.0023  Accuracy : 1.0000
Epoch : 262  Train Loss : 0.0081  Test Loss : 0.0022  Accuracy : 1.0000
Epoch : 264  Train Loss : 0.0075  Test Loss : 0.0022  Accuracy : 1.0000
Epoch : 266  Train Loss : 0.0065  Test Loss : 0.0021  Accuracy : 1.0000
Epoch : 268  Train Loss : 0.0073  Test Loss : 0.0021  Accuracy : 1.0000
Epoch : 270  Train Loss : 0.0074  Test Loss : 0.0020  Accuracy : 1.0000
Epoch : 272  Train Loss : 0.0070  Test Loss : 0.0020  Accuracy : 1.0000
Epoch : 274  Train Loss : 0.0071  Test Loss : 0.0020  Accuracy : 1.0000
Epoch : 276  Train Loss : 0.0069  Test Loss : 0.0019  Accuracy : 1.0000
Epoch : 278  Train Loss : 0.0067  Test Loss : 0.0019  Accuracy : 1.0000
Epoch : 280  Train Loss : 0.0065  Test Loss : 0.0018  Accuracy : 1.0000
Epoch : 282  Train Loss : 0.0069  Test Loss : 0.0018  Accuracy : 1.0000
Epoch : 284  Train Loss : 0.0064  Test Loss : 0.0018  Accuracy : 1.0000
Epoch : 286  Train Loss : 0.0055  Test Loss : 0.0017  Accuracy : 1.0000
Epoch : 288  Train Loss : 0.0063  Test Loss : 0.0017  Accuracy : 1.0000
Epoch : 290  Train Loss : 0.0070  Test Loss : 0.0017  Accuracy : 1.0000
Epoch : 292  Train Loss : 0.0067  Test Loss : 0.0016  Accuracy : 1.0000
Epoch : 294  Train Loss : 0.0056  Test Loss : 0.0016  Accuracy : 1.0000
Epoch : 296  Train Loss : 0.0065  Test Loss : 0.0016  Accuracy : 1.0000
Epoch : 298  Train Loss : 0.0057  Test Loss : 0.0015  Accuracy : 1.0000
Epoch : 300  Train Loss : 0.0055  Test Loss : 0.0015  Accuracy : 1.0000
Epoch : 302  Train Loss : 0.0057  Test Loss : 0.0015  Accuracy : 1.0000
Epoch : 304  Train Loss : 0.0064  Test Loss : 0.0015  Accuracy : 1.0000
Epoch : 306  Train Loss : 0.0056  Test Loss : 0.0014  Accuracy : 1.0000
Epoch : 308  Train Loss : 0.0055  Test Loss : 0.0014  Accuracy : 1.0000
Epoch : 310  Train Loss : 0.0063  Test Loss : 0.0014  Accuracy : 1.0000
Epoch : 312  Train Loss : 0.0054  Test Loss : 0.0014  Accuracy : 1.0000
Epoch : 314  Train Loss : 0.0057  Test Loss : 0.0013  Accuracy : 1.0000
Epoch : 316  Train Loss : 0.0052  Test Loss : 0.0013  Accuracy : 1.0000
Epoch : 318  Train Loss : 0.0053  Test Loss : 0.0013  Accuracy : 1.0000
Epoch : 320  Train Loss : 0.0045  Test Loss : 0.0013  Accuracy : 1.0000
Epoch : 322  Train Loss : 0.0058  Test Loss : 0.0012  Accuracy : 1.0000
Epoch : 324  Train Loss : 0.0049  Test Loss : 0.0012  Accuracy : 1.0000
Epoch : 326  Train Loss : 0.0049  Test Loss : 0.0012  Accuracy : 1.0000
Epoch : 328  Train Loss : 0.0051  Test Loss : 0.0012  Accuracy : 1.0000
Epoch : 330  Train Loss : 0.0044  Test Loss : 0.0012  Accuracy : 1.0000
Epoch : 332  Train Loss : 0.0048  Test Loss : 0.0011  Accuracy : 1.0000
Epoch : 334  Train Loss : 0.0048  Test Loss : 0.0011  Accuracy : 1.0000
Epoch : 336  Train Loss : 0.0047  Test Loss : 0.0011  Accuracy : 1.0000
Epoch : 338  Train Loss : 0.0042  Test Loss : 0.0011  Accuracy : 1.0000
Epoch : 340  Train Loss : 0.0049  Test Loss : 0.0011  Accuracy : 1.0000
Epoch : 342  Train Loss : 0.0052  Test Loss : 0.0011  Accuracy : 1.0000
Epoch : 344  Train Loss : 0.0045  Test Loss : 0.0010  Accuracy : 1.0000
Epoch : 346  Train Loss : 0.0040  Test Loss : 0.0010  Accuracy : 1.0000
Epoch : 348  Train Loss : 0.0042  Test Loss : 0.0010  Accuracy : 1.0000
Epoch : 350  Train Loss : 0.0041  Test Loss : 0.0010  Accuracy : 1.0000
Epoch : 352  Train Loss : 0.0053  Test Loss : 0.0010  Accuracy : 1.0000
Epoch : 354  Train Loss : 0.0037  Test Loss : 0.0010  Accuracy : 1.0000
Epoch : 356  Train Loss : 0.0038  Test Loss : 0.0009  Accuracy : 1.0000
Epoch : 358  Train Loss : 0.0037  Test Loss : 0.0009  Accuracy : 1.0000
Epoch : 360  Train Loss : 0.0047  Test Loss : 0.0009  Accuracy : 1.0000
Epoch : 362  Train Loss : 0.0047  Test Loss : 0.0009  Accuracy : 1.0000
Epoch : 364  Train Loss : 0.0052  Test Loss : 0.0009  Accuracy : 1.0000
Epoch : 366  Train Loss : 0.0050  Test Loss : 0.0009  Accuracy : 1.0000
Epoch : 368  Train Loss : 0.0038  Test Loss : 0.0009  Accuracy : 1.0000
Epoch : 370  Train Loss : 0.0040  Test Loss : 0.0009  Accuracy : 1.0000
Epoch : 372  Train Loss : 0.0037  Test Loss : 0.0008  Accuracy : 1.0000
Epoch : 374  Train Loss : 0.0034  Test Loss : 0.0008  Accuracy : 1.0000
Epoch : 376  Train Loss : 0.0040  Test Loss : 0.0008  Accuracy : 1.0000
Epoch : 378  Train Loss : 0.0043  Test Loss : 0.0008  Accuracy : 1.0000
Epoch : 380  Train Loss : 0.0037  Test Loss : 0.0008  Accuracy : 1.0000
Epoch : 382  Train Loss : 0.0044  Test Loss : 0.0008  Accuracy : 1.0000
Epoch : 384  Train Loss : 0.0033  Test Loss : 0.0008  Accuracy : 1.0000
Epoch : 386  Train Loss : 0.0037  Test Loss : 0.0008  Accuracy : 1.0000
Epoch : 388  Train Loss : 0.0038  Test Loss : 0.0008  Accuracy : 1.0000
Epoch : 390  Train Loss : 0.0037  Test Loss : 0.0007  Accuracy : 1.0000
Epoch : 392  Train Loss : 0.0041  Test Loss : 0.0007  Accuracy : 1.0000
Epoch : 394  Train Loss : 0.0037  Test Loss : 0.0007  Accuracy : 1.0000
Epoch : 396  Train Loss : 0.0043  Test Loss : 0.0007  Accuracy : 1.0000
Epoch : 398  Train Loss : 0.0044  Test Loss : 0.0007  Accuracy : 1.0000
Epoch : 400  Train Loss : 0.0040  Test Loss : 0.0007  Accuracy : 1.0000
Epoch : 402  Train Loss : 0.0030  Test Loss : 0.0007  Accuracy : 1.0000
Epoch : 404  Train Loss : 0.0034  Test Loss : 0.0007  Accuracy : 1.0000
Epoch : 406  Train Loss : 0.0028  Test Loss : 0.0007  Accuracy : 1.0000
Epoch : 408  Train Loss : 0.0032  Test Loss : 0.0007  Accuracy : 1.0000
Epoch : 410  Train Loss : 0.0032  Test Loss : 0.0007  Accuracy : 1.0000
Epoch : 412  Train Loss : 0.0032  Test Loss : 0.0007  Accuracy : 1.0000
Epoch : 414  Train Loss : 0.0032  Test Loss : 0.0006  Accuracy : 1.0000
Epoch : 416  Train Loss : 0.0028  Test Loss : 0.0006  Accuracy : 1.0000
Epoch : 418  Train Loss : 0.0040  Test Loss : 0.0006  Accuracy : 1.0000
Epoch : 420  Train Loss : 0.0034  Test Loss : 0.0006  Accuracy : 1.0000
Epoch : 422  Train Loss : 0.0029  Test Loss : 0.0006  Accuracy : 1.0000
Epoch : 424  Train Loss : 0.0038  Test Loss : 0.0006  Accuracy : 1.0000
Epoch : 426  Train Loss : 0.0034  Test Loss : 0.0006  Accuracy : 1.0000
Epoch : 428  Train Loss : 0.0029  Test Loss : 0.0006  Accuracy : 1.0000
Epoch : 430  Train Loss : 0.0029  Test Loss : 0.0006  Accuracy : 1.0000
Epoch : 432  Train Loss : 0.0033  Test Loss : 0.0006  Accuracy : 1.0000
Epoch : 434  Train Loss : 0.0033  Test Loss : 0.0006  Accuracy : 1.0000
Epoch : 436  Train Loss : 0.0029  Test Loss : 0.0006  Accuracy : 1.0000
Epoch : 438  Train Loss : 0.0029  Test Loss : 0.0006  Accuracy : 1.0000
Epoch : 440  Train Loss : 0.0028  Test Loss : 0.0006  Accuracy : 1.0000
Epoch : 442  Train Loss : 0.0031  Test Loss : 0.0005  Accuracy : 1.0000
Epoch : 444  Train Loss : 0.0034  Test Loss : 0.0005  Accuracy : 1.0000
Epoch : 446  Train Loss : 0.0027  Test Loss : 0.0005  Accuracy : 1.0000
Epoch : 448  Train Loss : 0.0026  Test Loss : 0.0005  Accuracy : 1.0000
Epoch : 450  Train Loss : 0.0024  Test Loss : 0.0005  Accuracy : 1.0000
Epoch : 452  Train Loss : 0.0028  Test Loss : 0.0005  Accuracy : 1.0000
Epoch : 454  Train Loss : 0.0028  Test Loss : 0.0005  Accuracy : 1.0000
Epoch : 456  Train Loss : 0.0027  Test Loss : 0.0005  Accuracy : 1.0000
Epoch : 458  Train Loss : 0.0031  Test Loss : 0.0005  Accuracy : 1.0000
Epoch : 460  Train Loss : 0.0029  Test Loss : 0.0005  Accuracy : 1.0000
Epoch : 462  Train Loss : 0.0030  Test Loss : 0.0005  Accuracy : 1.0000
Epoch : 464  Train Loss : 0.0028  Test Loss : 0.0005  Accuracy : 1.0000
Epoch : 466  Train Loss : 0.0027  Test Loss : 0.0005  Accuracy : 1.0000
Epoch : 468  Train Loss : 0.0026  Test Loss : 0.0005  Accuracy : 1.0000
Epoch : 470  Train Loss : 0.0029  Test Loss : 0.0005  Accuracy : 1.0000
Epoch : 472  Train Loss : 0.0029  Test Loss : 0.0005  Accuracy : 1.0000
Epoch : 474  Train Loss : 0.0025  Test Loss : 0.0005  Accuracy : 1.0000
Epoch : 476  Train Loss : 0.0022  Test Loss : 0.0005  Accuracy : 1.0000
Epoch : 478  Train Loss : 0.0028  Test Loss : 0.0005  Accuracy : 1.0000
Epoch : 480  Train Loss : 0.0026  Test Loss : 0.0004  Accuracy : 1.0000
Epoch : 482  Train Loss : 0.0028  Test Loss : 0.0004  Accuracy : 1.0000
Epoch : 484  Train Loss : 0.0024  Test Loss : 0.0004  Accuracy : 1.0000
Epoch : 486  Train Loss : 0.0024  Test Loss : 0.0004  Accuracy : 1.0000
Epoch : 488  Train Loss : 0.0020  Test Loss : 0.0004  Accuracy : 1.0000
Epoch : 490  Train Loss : 0.0027  Test Loss : 0.0004  Accuracy : 1.0000
Epoch : 492  Train Loss : 0.0022  Test Loss : 0.0004  Accuracy : 1.0000
Epoch : 494  Train Loss : 0.0032  Test Loss : 0.0004  Accuracy : 1.0000
Epoch : 496  Train Loss : 0.0022  Test Loss : 0.0004  Accuracy : 1.0000
Epoch : 498  Train Loss : 0.0026  Test Loss : 0.0004  Accuracy : 1.0000

## now using df2

In [92]:
x2 = df2.drop(["Pulse_A_Upper"	, "Pulse_B_Upper" , "Pulse_C_Upper" ,	"Pulse_A_Lower" ,	"Pulse_B_Lower" ,	"Pulse_C_Lower"] , axis = 1)
x2.head()

   Torque_Nm  Flux_Wb  Angle_deg
0     20.867    1.046    211.048
1     26.941    0.638    132.754
2      0.745    0.723    224.578
3      1.956    0.161    154.833
4      0.522    0.269    299.427

In [93]:
y2 =  df2.drop(["Torque_Nm"	, "Flux_Wb" ,	"Angle_deg"] , axis = 1)
y2.head()

,Pulse_A_Upper,Pulse_B_Upper,Pulse_C_Upper,Pulse_A_Lower,Pulse_B_Lower,Pulse_C_Lower
0,0,1,0,1,1,0
1,0,1,0,1,0,1
2,0,1,0,1,1,0
3,0,1,0,1,0,1
4,0,1,1,0,1,0

In [94]:
x2["Angle_sin"] = np.sin(np.radians(x2["Angle_deg"]))
x2["Angle_cos"] = np.cos(np.radians(x2["Angle_deg"]))

In [95]:
x2.head()

   Torque_Nm  Flux_Wb  Angle_deg  Angle_sin  Angle_cos
0     20.867    1.046    211.048  -0.515756  -0.856736
1     26.941    0.638    132.754   0.734275  -0.678852
2      0.745    0.723    224.578  -0.701880  -0.712296
3      1.956    0.161    154.833   0.425258  -0.905072
4      0.522    0.269    299.427  -0.870982   0.491314

In [96]:
x2 = x2.drop(["Angle_deg"] , axis = 1)

In [97]:
from sklearn.model_selection import train_test_split
x2_train , x2_test , y2_train , y2_test = train_test_split(x2 , y2 , random_state = 1 , test_size = 0.3)

In [98]:
scaler = StandardScaler()
x2_train = scaler.fit_transform(x2_train)
x2_test = scaler.transform(x2_test)

In [101]:
import joblib
import os
os.mkdir("saved_models")
joblib.dump(scaler, "saved_models/scaler.pkl")

['saved_models/scaler.pkl']

In [102]:
x2_train = torch.tensor(x2_train, dtype=torch.float32)
x2_test = torch.tensor(x2_test, dtype=torch.float32)
y2_train = torch.tensor(y2_train.values, dtype=torch.float32)
y2_test = torch.tensor(y2_test.values, dtype=torch.float32)

In [103]:
x2_train

tensor([[-0.9327, -1.3734, -0.9611, -1.0985],
        [ 1.4968, -1.1011,  1.0341, -0.9007],
        [ 1.5707, -1.1899, -1.2114,  0.8315],
        ...,
        [-0.0547,  0.6087,  1.3614, -0.0273],
        [-0.3471, -0.5016, -0.4241,  1.3546],
        [ 0.7712, -1.4407, -1.3964,  0.5002]])

In [104]:
class MotorModel_1(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = nn.Linear(4 , 64)
        self.l2 = nn.Linear(64 , 128)
        self.l3 = nn.Linear(128 , 64)
        self.l4 = nn.Linear(64 , 6)
        self.r = nn.ReLU()
        self.d = nn.Dropout(0.15)
    def forward(self , x):
        return self.l4(self.d(self.r(self.l3(self.d(self.r(self.l2(self.d(self.r(self.l1(x))))))))))

In [105]:
m1 = MotorModel_1().to(device)

In [106]:
loss1 = nn.BCEWithLogitsLoss()

In [107]:
optimizer = optim.Adam(m1.parameters() , lr = 0.001)

In [108]:
train_step(m1 ,500 , acc , loss1 , optimizer , x2_train , y2_train , x2_test , y2_test)

  0%|          | 0/500 [00:00<?, ?it/s]

Epoch : 0  Train Loss : 0.6964  Test Loss : 0.6923  Accuracy : 0.5117
Epoch : 2  Train Loss : 0.6876  Test Loss : 0.6825  Accuracy : 0.5833
Epoch : 4  Train Loss : 0.6779  Test Loss : 0.6723  Accuracy : 0.6789
Epoch : 6  Train Loss : 0.6680  Test Loss : 0.6608  Accuracy : 0.7728
Epoch : 8  Train Loss : 0.6569  Test Loss : 0.6476  Accuracy : 0.8656
Epoch : 10  Train Loss : 0.6444  Test Loss : 0.6322  Accuracy : 0.8917
Epoch : 12  Train Loss : 0.6266  Test Loss : 0.6140  Accuracy : 0.9044
Epoch : 14  Train Loss : 0.6091  Test Loss : 0.5923  Accuracy : 0.9106
Epoch : 16  Train Loss : 0.5853  Test Loss : 0.5668  Accuracy : 0.9150
Epoch : 18  Train Loss : 0.5595  Test Loss : 0.5374  Accuracy : 0.9183
Epoch : 20  Train Loss : 0.5277  Test Loss : 0.5042  Accuracy : 0.9256
Epoch : 22  Train Loss : 0.4992  Test Loss : 0.4676  Accuracy : 0.9322
Epoch : 24  Train Loss : 0.4623  Test Loss : 0.4285  Accuracy : 0.9378
Epoch : 26  Train Loss : 0.4234  Test Loss : 0.3880  Accuracy : 0.9400
Epoch : 28  Train Loss : 0.3833  Test Loss : 0.3473  Accuracy : 0.9461
Epoch : 30  Train Loss : 0.3420  Test Loss : 0.3078  Accuracy : 0.9500
Epoch : 32  Train Loss : 0.3060  Test Loss : 0.2704  Accuracy : 0.9567
Epoch : 34  Train Loss : 0.2743  Test Loss : 0.2360  Accuracy : 0.9644
Epoch : 36  Train Loss : 0.2428  Test Loss : 0.2055  Accuracy : 0.9706
Epoch : 38  Train Loss : 0.2108  Test Loss : 0.1789  Accuracy : 0.9778
Epoch : 40  Train Loss : 0.1894  Test Loss : 0.1562  Accuracy : 0.9817
Epoch : 42  Train Loss : 0.1698  Test Loss : 0.1376  Accuracy : 0.9856
Epoch : 44  Train Loss : 0.1563  Test Loss : 0.1227  Accuracy : 0.9861
Epoch : 46  Train Loss : 0.1447  Test Loss : 0.1102  Accuracy : 0.9878
Epoch : 48  Train Loss : 0.1283  Test Loss : 0.0999  Accuracy : 0.9878
Epoch : 50  Train Loss : 0.1268  Test Loss : 0.0913  Accuracy : 0.9878
Epoch : 52  Train Loss : 0.1203  Test Loss : 0.0843  Accuracy : 0.9883
Epoch : 54  Train Loss : 0.1094  Test Loss : 0.0785  Accuracy : 0.9878
Epoch : 56  Train Loss : 0.1036  Test Loss : 0.0737  Accuracy : 0.9878
Epoch : 58  Train Loss : 0.1062  Test Loss : 0.0697  Accuracy : 0.9900
Epoch : 60  Train Loss : 0.0958  Test Loss : 0.0666  Accuracy : 0.9906
Epoch : 62  Train Loss : 0.1021  Test Loss : 0.0641  Accuracy : 0.9900
Epoch : 64  Train Loss : 0.0965  Test Loss : 0.0614  Accuracy : 0.9894
Epoch : 66  Train Loss : 0.0971  Test Loss : 0.0586  Accuracy : 0.9883
Epoch : 68  Train Loss : 0.0953  Test Loss : 0.0568  Accuracy : 0.9894
Epoch : 70  Train Loss : 0.0923  Test Loss : 0.0558  Accuracy : 0.9894
Epoch : 72  Train Loss : 0.0835  Test Loss : 0.0548  Accuracy : 0.9906
Epoch : 74  Train Loss : 0.0793  Test Loss : 0.0531  Accuracy : 0.9906
Epoch : 76  Train Loss : 0.0898  Test Loss : 0.0513  Accuracy : 0.9917
Epoch : 78  Train Loss : 0.0808  Test Loss : 0.0498  Accuracy : 0.9911
Epoch : 80  Train Loss : 0.0744  Test Loss : 0.0487  Accuracy : 0.9911
Epoch : 82  Train Loss : 0.0903  Test Loss : 0.0484  Accuracy : 0.9900
Epoch : 84  Train Loss : 0.0880  Test Loss : 0.0487  Accuracy : 0.9906
Epoch : 86  Train Loss : 0.0819  Test Loss : 0.0482  Accuracy : 0.9906
Epoch : 88  Train Loss : 0.0847  Test Loss : 0.0472  Accuracy : 0.9889
Epoch : 90  Train Loss : 0.0788  Test Loss : 0.0454  Accuracy : 0.9906
Epoch : 92  Train Loss : 0.0819  Test Loss : 0.0441  Accuracy : 0.9917
Epoch : 94  Train Loss : 0.0738  Test Loss : 0.0437  Accuracy : 0.9922
Epoch : 96  Train Loss : 0.0805  Test Loss : 0.0431  Accuracy : 0.9911
Epoch : 98  Train Loss : 0.0757  Test Loss : 0.0426  Accuracy : 0.9917
Epoch : 100  Train Loss : 0.0847  Test Loss : 0.0424  Accuracy : 0.9889
Epoch : 102  Train Loss : 0.0691  Test Loss : 0.0422  Accuracy : 0.9878
Epoch : 104  Train Loss : 0.0718  Test Loss : 0.0414  Accuracy : 0.9911
Epoch : 106  Train Loss : 0.0718  Test Loss : 0.0409  Accuracy : 0.9922
Epoch : 108  Train Loss : 0.0776  Test Loss : 0.0410  Accuracy : 0.9928
Epoch : 110  Train Loss : 0.0729  Test Loss : 0.0397  Accuracy : 0.9922
Epoch : 112  Train Loss : 0.0758  Test Loss : 0.0384  Accuracy : 0.9922
Epoch : 114  Train Loss : 0.0711  Test Loss : 0.0380  Accuracy : 0.9900
Epoch : 116  Train Loss : 0.0681  Test Loss : 0.0381  Accuracy : 0.9894
Epoch : 118  Train Loss : 0.0706  Test Loss : 0.0382  Accuracy : 0.9917
Epoch : 120  Train Loss : 0.0667  Test Loss : 0.0385  Accuracy : 0.9933
Epoch : 122  Train Loss : 0.0704  Test Loss : 0.0375  Accuracy : 0.9928
Epoch : 124  Train Loss : 0.0702  Test Loss : 0.0365  Accuracy : 0.9933
Epoch : 126  Train Loss : 0.0718  Test Loss : 0.0360  Accuracy : 0.9917
Epoch : 128  Train Loss : 0.0650  Test Loss : 0.0357  Accuracy : 0.9922
Epoch : 130  Train Loss : 0.0618  Test Loss : 0.0358  Accuracy : 0.9911
Epoch : 132  Train Loss : 0.0597  Test Loss : 0.0356  Accuracy : 0.9917
Epoch : 134  Train Loss : 0.0701  Test Loss : 0.0350  Accuracy : 0.9922
Epoch : 136  Train Loss : 0.0635  Test Loss : 0.0347  Accuracy : 0.9933
Epoch : 138  Train Loss : 0.0624  Test Loss : 0.0343  Accuracy : 0.9917
Epoch : 140  Train Loss : 0.0707  Test Loss : 0.0339  Accuracy : 0.9922
Epoch : 142  Train Loss : 0.0640  Test Loss : 0.0331  Accuracy : 0.9928
Epoch : 144  Train Loss : 0.0671  Test Loss : 0.0326  Accuracy : 0.9917
Epoch : 146  Train Loss : 0.0597  Test Loss : 0.0324  Accuracy : 0.9939
Epoch : 148  Train Loss : 0.0553  Test Loss : 0.0324  Accuracy : 0.9950
Epoch : 150  Train Loss : 0.0608  Test Loss : 0.0330  Accuracy : 0.9917
Epoch : 152  Train Loss : 0.0616  Test Loss : 0.0325  Accuracy : 0.9900
Epoch : 154  Train Loss : 0.0594  Test Loss : 0.0316  Accuracy : 0.9911
Epoch : 156  Train Loss : 0.0601  Test Loss : 0.0312  Accuracy : 0.9911
Epoch : 158  Train Loss : 0.0588  Test Loss : 0.0315  Accuracy : 0.9950
Epoch : 160  Train Loss : 0.0628  Test Loss : 0.0321  Accuracy : 0.9956
Epoch : 162  Train Loss : 0.0602  Test Loss : 0.0331  Accuracy : 0.9939
Epoch : 164  Train Loss : 0.0659  Test Loss : 0.0332  Accuracy : 0.9917
Epoch : 166  Train Loss : 0.0615  Test Loss : 0.0322  Accuracy : 0.9889
Epoch : 168  Train Loss : 0.0530  Test Loss : 0.0315  Accuracy : 0.9900
Epoch : 170  Train Loss : 0.0592  Test Loss : 0.0309  Accuracy : 0.9911
Epoch : 172  Train Loss : 0.0582  Test Loss : 0.0305  Accuracy : 0.9922
Epoch : 174  Train Loss : 0.0621  Test Loss : 0.0310  Accuracy : 0.9928
Epoch : 176  Train Loss : 0.0597  Test Loss : 0.0316  Accuracy : 0.9922
Epoch : 178  Train Loss : 0.0565  Test Loss : 0.0317  Accuracy : 0.9911
Epoch : 180  Train Loss : 0.0539  Test Loss : 0.0305  Accuracy : 0.9906
Epoch : 182  Train Loss : 0.0606  Test Loss : 0.0293  Accuracy : 0.9933
Epoch : 184  Train Loss : 0.0583  Test Loss : 0.0286  Accuracy : 0.9928
Epoch : 186  Train Loss : 0.0508  Test Loss : 0.0282  Accuracy : 0.9922
Epoch : 188  Train Loss : 0.0551  Test Loss : 0.0284  Accuracy : 0.9922
Epoch : 190  Train Loss : 0.0523  Test Loss : 0.0286  Accuracy : 0.9917
Epoch : 192  Train Loss : 0.0556  Test Loss : 0.0290  Accuracy : 0.9917
Epoch : 194  Train Loss : 0.0564  Test Loss : 0.0291  Accuracy : 0.9911
Epoch : 196  Train Loss : 0.0569  Test Loss : 0.0286  Accuracy : 0.9933
Epoch : 198  Train Loss : 0.0500  Test Loss : 0.0278  Accuracy : 0.9933
Epoch : 200  Train Loss : 0.0517  Test Loss : 0.0279  Accuracy : 0.9911
Epoch : 202  Train Loss : 0.0524  Test Loss : 0.0278  Accuracy : 0.9911
Epoch : 204  Train Loss : 0.0573  Test Loss : 0.0282  Accuracy : 0.9933
Epoch : 206  Train Loss : 0.0583  Test Loss : 0.0290  Accuracy : 0.9933
Epoch : 208  Train Loss : 0.0570  Test Loss : 0.0293  Accuracy : 0.9933
Epoch : 210  Train Loss : 0.0557  Test Loss : 0.0287  Accuracy : 0.9911
Epoch : 212  Train Loss : 0.0571  Test Loss : 0.0276  Accuracy : 0.9928
Epoch : 214  Train Loss : 0.0550  Test Loss : 0.0271  Accuracy : 0.9928
Epoch : 216  Train Loss : 0.0634  Test Loss : 0.0270  Accuracy : 0.9922
Epoch : 218  Train Loss : 0.0576  Test Loss : 0.0268  Accuracy : 0.9939
Epoch : 220  Train Loss : 0.0472  Test Loss : 0.0270  Accuracy : 0.9933
Epoch : 222  Train Loss : 0.0610  Test Loss : 0.0277  Accuracy : 0.9911
Epoch : 224  Train Loss : 0.0450  Test Loss : 0.0284  Accuracy : 0.9900
Epoch : 226  Train Loss : 0.0496  Test Loss : 0.0271  Accuracy : 0.9911
Epoch : 228  Train Loss : 0.0509  Test Loss : 0.0257  Accuracy : 0.9933
Epoch : 230  Train Loss : 0.0526  Test Loss : 0.0251  Accuracy : 0.9928
Epoch : 232  Train Loss : 0.0512  Test Loss : 0.0249  Accuracy : 0.9933
Epoch : 234  Train Loss : 0.0536  Test Loss : 0.0253  Accuracy : 0.9922
Epoch : 236  Train Loss : 0.0489  Test Loss : 0.0258  Accuracy : 0.9917
Epoch : 238  Train Loss : 0.0445  Test Loss : 0.0258  Accuracy : 0.9922
Epoch : 240  Train Loss : 0.0478  Test Loss : 0.0263  Accuracy : 0.9939
Epoch : 242  Train Loss : 0.0500  Test Loss : 0.0259  Accuracy : 0.9928
Epoch : 244  Train Loss : 0.0554  Test Loss : 0.0249  Accuracy : 0.9917
Epoch : 246  Train Loss : 0.0504  Test Loss : 0.0241  Accuracy : 0.9939
Epoch : 248  Train Loss : 0.0424  Test Loss : 0.0244  Accuracy : 0.9933
Epoch : 250  Train Loss : 0.0478  Test Loss : 0.0252  Accuracy : 0.9928
Epoch : 252  Train Loss : 0.0578  Test Loss : 0.0254  Accuracy : 0.9922
Epoch : 254  Train Loss : 0.0516  Test Loss : 0.0244  Accuracy : 0.9944
Epoch : 256  Train Loss : 0.0458  Test Loss : 0.0240  Accuracy : 0.9944
Epoch : 258  Train Loss : 0.0451  Test Loss : 0.0242  Accuracy : 0.9933
Epoch : 260  Train Loss : 0.0447  Test Loss : 0.0249  Accuracy : 0.9922
Epoch : 262  Train Loss : 0.0492  Test Loss : 0.0252  Accuracy : 0.9922
Epoch : 264  Train Loss : 0.0543  Test Loss : 0.0252  Accuracy : 0.9939
Epoch : 266  Train Loss : 0.0512  Test Loss : 0.0243  Accuracy : 0.9944
Epoch : 268  Train Loss : 0.0506  Test Loss : 0.0234  Accuracy : 0.9933
Epoch : 270  Train Loss : 0.0543  Test Loss : 0.0235  Accuracy : 0.9933
Epoch : 272  Train Loss : 0.0498  Test Loss : 0.0237  Accuracy : 0.9928
Epoch : 274  Train Loss : 0.0445  Test Loss : 0.0240  Accuracy : 0.9928
Epoch : 276  Train Loss : 0.0394  Test Loss : 0.0251  Accuracy : 0.9939
Epoch : 278  Train Loss : 0.0392  Test Loss : 0.0257  Accuracy : 0.9944
Epoch : 280  Train Loss : 0.0479  Test Loss : 0.0249  Accuracy : 0.9956
Epoch : 282  Train Loss : 0.0513  Test Loss : 0.0231  Accuracy : 0.9967
Epoch : 284  Train Loss : 0.0467  Test Loss : 0.0227  Accuracy : 0.9922
Epoch : 286  Train Loss : 0.0411  Test Loss : 0.0233  Accuracy : 0.9900
Epoch : 288  Train Loss : 0.0513  Test Loss : 0.0229  Accuracy : 0.9911
Epoch : 290  Train Loss : 0.0490  Test Loss : 0.0240  Accuracy : 0.9944
Epoch : 292  Train Loss : 0.0464  Test Loss : 0.0265  Accuracy : 0.9933
Epoch : 294  Train Loss : 0.0471  Test Loss : 0.0260  Accuracy : 0.9928
Epoch : 296  Train Loss : 0.0534  Test Loss : 0.0235  Accuracy : 0.9944
Epoch : 298  Train Loss : 0.0385  Test Loss : 0.0224  Accuracy : 0.9933
Epoch : 300  Train Loss : 0.0442  Test Loss : 0.0226  Accuracy : 0.9922
Epoch : 302  Train Loss : 0.0513  Test Loss : 0.0225  Accuracy : 0.9922
Epoch : 304  Train Loss : 0.0453  Test Loss : 0.0229  Accuracy : 0.9928
Epoch : 306  Train Loss : 0.0488  Test Loss : 0.0239  Accuracy : 0.9922
Epoch : 308  Train Loss : 0.0503  Test Loss : 0.0245  Accuracy : 0.9939
Epoch : 310  Train Loss : 0.0406  Test Loss : 0.0239  Accuracy : 0.9928
Epoch : 312  Train Loss : 0.0462  Test Loss : 0.0226  Accuracy : 0.9933
Epoch : 314  Train Loss : 0.0414  Test Loss : 0.0221  Accuracy : 0.9933
Epoch : 316  Train Loss : 0.0448  Test Loss : 0.0220  Accuracy : 0.9933
Epoch : 318  Train Loss : 0.0484  Test Loss : 0.0220  Accuracy : 0.9933
Epoch : 320  Train Loss : 0.0407  Test Loss : 0.0221  Accuracy : 0.9944
Epoch : 322  Train Loss : 0.0407  Test Loss : 0.0226  Accuracy : 0.9961
Epoch : 324  Train Loss : 0.0355  Test Loss : 0.0237  Accuracy : 0.9917
Epoch : 326  Train Loss : 0.0443  Test Loss : 0.0246  Accuracy : 0.9911
Epoch : 328  Train Loss : 0.0378  Test Loss : 0.0243  Accuracy : 0.9911
Epoch : 330  Train Loss : 0.0393  Test Loss : 0.0227  Accuracy : 0.9944
Epoch : 332  Train Loss : 0.0414  Test Loss : 0.0216  Accuracy : 0.9944
Epoch : 334  Train Loss : 0.0381  Test Loss : 0.0213  Accuracy : 0.9944
Epoch : 336  Train Loss : 0.0379  Test Loss : 0.0219  Accuracy : 0.9944
Epoch : 338  Train Loss : 0.0481  Test Loss : 0.0220  Accuracy : 0.9956
Epoch : 340  Train Loss : 0.0482  Test Loss : 0.0219  Accuracy : 0.9933
Epoch : 342  Train Loss : 0.0447  Test Loss : 0.0221  Accuracy : 0.9933
Epoch : 344  Train Loss : 0.0395  Test Loss : 0.0222  Accuracy : 0.9944
Epoch : 346  Train Loss : 0.0426  Test Loss : 0.0224  Accuracy : 0.9956
Epoch : 348  Train Loss : 0.0386  Test Loss : 0.0229  Accuracy : 0.9956
Epoch : 350  Train Loss : 0.0390  Test Loss : 0.0231  Accuracy : 0.9956
Epoch : 352  Train Loss : 0.0428  Test Loss : 0.0226  Accuracy : 0.9944
Epoch : 354  Train Loss : 0.0409  Test Loss : 0.0218  Accuracy : 0.9922
Epoch : 356  Train Loss : 0.0398  Test Loss : 0.0210  Accuracy : 0.9933
Epoch : 358  Train Loss : 0.0404  Test Loss : 0.0202  Accuracy : 0.9933
Epoch : 360  Train Loss : 0.0368  Test Loss : 0.0198  Accuracy : 0.9933
Epoch : 362  Train Loss : 0.0418  Test Loss : 0.0195  Accuracy : 0.9944
Epoch : 364  Train Loss : 0.0454  Test Loss : 0.0201  Accuracy : 0.9956
Epoch : 366  Train Loss : 0.0437  Test Loss : 0.0208  Accuracy : 0.9961
Epoch : 368  Train Loss : 0.0356  Test Loss : 0.0201  Accuracy : 0.9956
Epoch : 370  Train Loss : 0.0418  Test Loss : 0.0195  Accuracy : 0.9956
Epoch : 372  Train Loss : 0.0375  Test Loss : 0.0193  Accuracy : 0.9956
Epoch : 374  Train Loss : 0.0436  Test Loss : 0.0191  Accuracy : 0.9944
Epoch : 376  Train Loss : 0.0461  Test Loss : 0.0189  Accuracy : 0.9933
Epoch : 378  Train Loss : 0.0386  Test Loss : 0.0192  Accuracy : 0.9933
Epoch : 380  Train Loss : 0.0395  Test Loss : 0.0194  Accuracy : 0.9944
Epoch : 382  Train Loss : 0.0328  Test Loss : 0.0193  Accuracy : 0.9950
Epoch : 384  Train Loss : 0.0423  Test Loss : 0.0191  Accuracy : 0.9950
Epoch : 386  Train Loss : 0.0359  Test Loss : 0.0191  Accuracy : 0.9961
Epoch : 388  Train Loss : 0.0383  Test Loss : 0.0194  Accuracy : 0.9967
Epoch : 390  Train Loss : 0.0362  Test Loss : 0.0194  Accuracy : 0.9967
Epoch : 392  Train Loss : 0.0380  Test Loss : 0.0196  Accuracy : 0.9961
Epoch : 394  Train Loss : 0.0392  Test Loss : 0.0203  Accuracy : 0.9961
Epoch : 396  Train Loss : 0.0337  Test Loss : 0.0212  Accuracy : 0.9956
Epoch : 398  Train Loss : 0.0296  Test Loss : 0.0217  Accuracy : 0.9944
Epoch : 400  Train Loss : 0.0317  Test Loss : 0.0203  Accuracy : 0.9961
Epoch : 402  Train Loss : 0.0366  Test Loss : 0.0188  Accuracy : 0.9939
Epoch : 404  Train Loss : 0.0353  Test Loss : 0.0181  Accuracy : 0.9944
Epoch : 406  Train Loss : 0.0354  Test Loss : 0.0178  Accuracy : 0.9933
Epoch : 408  Train Loss : 0.0312  Test Loss : 0.0179  Accuracy : 0.9944
Epoch : 410  Train Loss : 0.0365  Test Loss : 0.0183  Accuracy : 0.9978
Epoch : 412  Train Loss : 0.0294  Test Loss : 0.0191  Accuracy : 0.9967
Epoch : 414  Train Loss : 0.0333  Test Loss : 0.0196  Accuracy : 0.9967
Epoch : 416  Train Loss : 0.0350  Test Loss : 0.0185  Accuracy : 0.9956
Epoch : 418  Train Loss : 0.0406  Test Loss : 0.0175  Accuracy : 0.9944
Epoch : 420  Train Loss : 0.0335  Test Loss : 0.0165  Accuracy : 0.9944
Epoch : 422  Train Loss : 0.0323  Test Loss : 0.0163  Accuracy : 0.9944
Epoch : 424  Train Loss : 0.0348  Test Loss : 0.0168  Accuracy : 0.9944
Epoch : 426  Train Loss : 0.0360  Test Loss : 0.0176  Accuracy : 0.9933
Epoch : 428  Train Loss : 0.0300  Test Loss : 0.0186  Accuracy : 0.9961
Epoch : 430  Train Loss : 0.0283  Test Loss : 0.0193  Accuracy : 0.9950
Epoch : 432  Train Loss : 0.0374  Test Loss : 0.0192  Accuracy : 0.9956
Epoch : 434  Train Loss : 0.0248  Test Loss : 0.0183  Accuracy : 0.9967
Epoch : 436  Train Loss : 0.0324  Test Loss : 0.0173  Accuracy : 0.9967
Epoch : 438  Train Loss : 0.0295  Test Loss : 0.0166  Accuracy : 0.9944
Epoch : 440  Train Loss : 0.0271  Test Loss : 0.0165  Accuracy : 0.9944
Epoch : 442  Train Loss : 0.0291  Test Loss : 0.0168  Accuracy : 0.9944
Epoch : 444  Train Loss : 0.0343  Test Loss : 0.0169  Accuracy : 0.9922
Epoch : 446  Train Loss : 0.0362  Test Loss : 0.0167  Accuracy : 0.9967
Epoch : 448  Train Loss : 0.0364  Test Loss : 0.0171  Accuracy : 0.9956
Epoch : 450  Train Loss : 0.0341  Test Loss : 0.0171  Accuracy : 0.9956
Epoch : 452  Train Loss : 0.0339  Test Loss : 0.0165  Accuracy : 0.9967
Epoch : 454  Train Loss : 0.0301  Test Loss : 0.0163  Accuracy : 0.9967
Epoch : 456  Train Loss : 0.0418  Test Loss : 0.0164  Accuracy : 0.9956
Epoch : 458  Train Loss : 0.0300  Test Loss : 0.0164  Accuracy : 0.9956
Epoch : 460  Train Loss : 0.0345  Test Loss : 0.0164  Accuracy : 0.9967
Epoch : 462  Train Loss : 0.0307  Test Loss : 0.0168  Accuracy : 0.9961
Epoch : 464  Train Loss : 0.0285  Test Loss : 0.0173  Accuracy : 0.9956
Epoch : 466  Train Loss : 0.0288  Test Loss : 0.0173  Accuracy : 0.9956
Epoch : 468  Train Loss : 0.0291  Test Loss : 0.0166  Accuracy : 0.9956
Epoch : 470  Train Loss : 0.0408  Test Loss : 0.0163  Accuracy : 0.9956
Epoch : 472  Train Loss : 0.0317  Test Loss : 0.0160  Accuracy : 0.9967
Epoch : 474  Train Loss : 0.0300  Test Loss : 0.0159  Accuracy : 0.9967
Epoch : 476  Train Loss : 0.0376  Test Loss : 0.0160  Accuracy : 0.9961
Epoch : 478  Train Loss : 0.0324  Test Loss : 0.0163  Accuracy : 0.9956
Epoch : 480  Train Loss : 0.0255  Test Loss : 0.0166  Accuracy : 0.9956
Epoch : 482  Train Loss : 0.0315  Test Loss : 0.0164  Accuracy : 0.9967
Epoch : 484  Train Loss : 0.0324  Test Loss : 0.0165  Accuracy : 0.9967
Epoch : 486  Train Loss : 0.0269  Test Loss : 0.0162  Accuracy : 0.9967
Epoch : 488  Train Loss : 0.0283  Test Loss : 0.0159  Accuracy : 0.9967
Epoch : 490  Train Loss : 0.0345  Test Loss : 0.0157  Accuracy : 0.9944
Epoch : 492  Train Loss : 0.0311  Test Loss : 0.0154  Accuracy : 0.9944
Epoch : 494  Train Loss : 0.0272  Test Loss : 0.0158  Accuracy : 0.9967
Epoch : 496  Train Loss : 0.0426  Test Loss : 0.0166  Accuracy : 0.9967
Epoch : 498  Train Loss : 0.0305  Test Loss : 0.0172  Accuracy : 0.9972

In [109]:
import os
os.makedirs("saved_models", exist_ok=True)
torch.save(m1.state_dict(), "saved_models/m1.pth")

In [110]:
class DeepResNet(nn.Module):

    def __init__(self):

        super().__init__()
        self.input = nn.Linear(4, 64)
        self.block1 = ResidualBlock(64)
        self.block2 = ResidualBlock(64)
        self.output = nn.Linear(64, 6)
        self.relu = nn.ReLU()
    def forward(self, x):
        x = self.relu(self.input(x))
        x = self.block1(x)
        x = self.block2(x)
        x = self.output(x)
        return x

In [111]:
m2 = DeepResNet().to(device)

In [112]:
op = optim.Adam(m2.parameters() , lr = 0.001)

In [113]:
train_step(m2 ,500 , acc , loss , op , x2_train , y2_train , x2_test , y2_test)

  0%|          | 0/500 [00:00<?, ?it/s]

Epoch : 0  Train Loss : 0.7065  Test Loss : 0.6997  Accuracy : 0.5294
Epoch : 2  Train Loss : 0.6900  Test Loss : 0.6838  Accuracy : 0.5917
Epoch : 4  Train Loss : 0.6743  Test Loss : 0.6685  Accuracy : 0.6511
Epoch : 6  Train Loss : 0.6591  Test Loss : 0.6532  Accuracy : 0.7106
Epoch : 8  Train Loss : 0.6438  Test Loss : 0.6376  Accuracy : 0.7672
Epoch : 10  Train Loss : 0.6279  Test Loss : 0.6212  Accuracy : 0.8100
Epoch : 12  Train Loss : 0.6113  Test Loss : 0.6038  Accuracy : 0.8433
Epoch : 14  Train Loss : 0.5936  Test Loss : 0.5850  Accuracy : 0.8611
Epoch : 16  Train Loss : 0.5744  Test Loss : 0.5644  Accuracy : 0.8694
Epoch : 18  Train Loss : 0.5532  Test Loss : 0.5414  Accuracy : 0.8883
Epoch : 20  Train Loss : 0.5296  Test Loss : 0.5159  Accuracy : 0.9033
Epoch : 22  Train Loss : 0.5033  Test Loss : 0.4877  Accuracy : 0.9172
Epoch : 24  Train Loss : 0.4744  Test Loss : 0.4570  Accuracy : 0.9233
Epoch : 26  Train Loss : 0.4430  Test Loss : 0.4240  Accuracy : 0.9306
Epoch : 28  Train Loss : 0.4094  Test Loss : 0.3889  Accuracy : 0.9367
Epoch : 30  Train Loss : 0.3738  Test Loss : 0.3524  Accuracy : 0.9411
Epoch : 32  Train Loss : 0.3369  Test Loss : 0.3153  Accuracy : 0.9478
Epoch : 34  Train Loss : 0.2996  Test Loss : 0.2789  Accuracy : 0.9539
Epoch : 36  Train Loss : 0.2629  Test Loss : 0.2439  Accuracy : 0.9583
Epoch : 38  Train Loss : 0.2281  Test Loss : 0.2116  Accuracy : 0.9617
Epoch : 40  Train Loss : 0.1963  Test Loss : 0.1825  Accuracy : 0.9628
Epoch : 42  Train Loss : 0.1680  Test Loss : 0.1567  Accuracy : 0.9644
Epoch : 44  Train Loss : 0.1430  Test Loss : 0.1341  Accuracy : 0.9672
Epoch : 46  Train Loss : 0.1214  Test Loss : 0.1147  Accuracy : 0.9733
Epoch : 48  Train Loss : 0.1030  Test Loss : 0.0989  Accuracy : 0.9772
Epoch : 50  Train Loss : 0.0880  Test Loss : 0.0867  Accuracy : 0.9811
Epoch : 52  Train Loss : 0.0762  Test Loss : 0.0769  Accuracy : 0.9839
Epoch : 54  Train Loss : 0.0668  Test Loss : 0.0685  Accuracy : 0.9872
Epoch : 56  Train Loss : 0.0591  Test Loss : 0.0618  Accuracy : 0.9867
Epoch : 58  Train Loss : 0.0528  Test Loss : 0.0565  Accuracy : 0.9872
Epoch : 60  Train Loss : 0.0476  Test Loss : 0.0516  Accuracy : 0.9894
Epoch : 62  Train Loss : 0.0432  Test Loss : 0.0472  Accuracy : 0.9900
Epoch : 64  Train Loss : 0.0394  Test Loss : 0.0440  Accuracy : 0.9900
Epoch : 66  Train Loss : 0.0364  Test Loss : 0.0414  Accuracy : 0.9900
Epoch : 68  Train Loss : 0.0336  Test Loss : 0.0392  Accuracy : 0.9900
Epoch : 70  Train Loss : 0.0312  Test Loss : 0.0375  Accuracy : 0.9900
Epoch : 72  Train Loss : 0.0292  Test Loss : 0.0360  Accuracy : 0.9900
Epoch : 74  Train Loss : 0.0273  Test Loss : 0.0343  Accuracy : 0.9917
Epoch : 76  Train Loss : 0.0256  Test Loss : 0.0327  Accuracy : 0.9928
Epoch : 78  Train Loss : 0.0241  Test Loss : 0.0313  Accuracy : 0.9933
Epoch : 80  Train Loss : 0.0228  Test Loss : 0.0298  Accuracy : 0.9939
Epoch : 82  Train Loss : 0.0216  Test Loss : 0.0286  Accuracy : 0.9944
Epoch : 84  Train Loss : 0.0205  Test Loss : 0.0276  Accuracy : 0.9944
Epoch : 86  Train Loss : 0.0195  Test Loss : 0.0268  Accuracy : 0.9950
Epoch : 88  Train Loss : 0.0185  Test Loss : 0.0261  Accuracy : 0.9944
Epoch : 90  Train Loss : 0.0176  Test Loss : 0.0252  Accuracy : 0.9939
Epoch : 92  Train Loss : 0.0168  Test Loss : 0.0246  Accuracy : 0.9939
Epoch : 94  Train Loss : 0.0161  Test Loss : 0.0241  Accuracy : 0.9939
Epoch : 96  Train Loss : 0.0154  Test Loss : 0.0237  Accuracy : 0.9944
Epoch : 98  Train Loss : 0.0147  Test Loss : 0.0231  Accuracy : 0.9944
Epoch : 100  Train Loss : 0.0141  Test Loss : 0.0226  Accuracy : 0.9950
Epoch : 102  Train Loss : 0.0135  Test Loss : 0.0220  Accuracy : 0.9950
Epoch : 104  Train Loss : 0.0129  Test Loss : 0.0216  Accuracy : 0.9956
Epoch : 106  Train Loss : 0.0124  Test Loss : 0.0213  Accuracy : 0.9956
Epoch : 108  Train Loss : 0.0119  Test Loss : 0.0210  Accuracy : 0.9956
Epoch : 110  Train Loss : 0.0114  Test Loss : 0.0206  Accuracy : 0.9956
Epoch : 112  Train Loss : 0.0109  Test Loss : 0.0202  Accuracy : 0.9956
Epoch : 114  Train Loss : 0.0105  Test Loss : 0.0199  Accuracy : 0.9956
Epoch : 116  Train Loss : 0.0101  Test Loss : 0.0196  Accuracy : 0.9956
Epoch : 118  Train Loss : 0.0097  Test Loss : 0.0194  Accuracy : 0.9956
Epoch : 120  Train Loss : 0.0093  Test Loss : 0.0191  Accuracy : 0.9956
Epoch : 122  Train Loss : 0.0089  Test Loss : 0.0189  Accuracy : 0.9956
Epoch : 124  Train Loss : 0.0086  Test Loss : 0.0187  Accuracy : 0.9956
Epoch : 126  Train Loss : 0.0083  Test Loss : 0.0186  Accuracy : 0.9956
Epoch : 128  Train Loss : 0.0080  Test Loss : 0.0184  Accuracy : 0.9956
Epoch : 130  Train Loss : 0.0077  Test Loss : 0.0182  Accuracy : 0.9956
Epoch : 132  Train Loss : 0.0074  Test Loss : 0.0180  Accuracy : 0.9956
Epoch : 134  Train Loss : 0.0071  Test Loss : 0.0179  Accuracy : 0.9956
Epoch : 136  Train Loss : 0.0069  Test Loss : 0.0177  Accuracy : 0.9956
Epoch : 138  Train Loss : 0.0066  Test Loss : 0.0176  Accuracy : 0.9956
Epoch : 140  Train Loss : 0.0064  Test Loss : 0.0175  Accuracy : 0.9956
Epoch : 142  Train Loss : 0.0062  Test Loss : 0.0174  Accuracy : 0.9956
Epoch : 144  Train Loss : 0.0059  Test Loss : 0.0173  Accuracy : 0.9956
Epoch : 146  Train Loss : 0.0057  Test Loss : 0.0172  Accuracy : 0.9956
Epoch : 148  Train Loss : 0.0055  Test Loss : 0.0171  Accuracy : 0.9956
Epoch : 150  Train Loss : 0.0054  Test Loss : 0.0170  Accuracy : 0.9956
Epoch : 152  Train Loss : 0.0052  Test Loss : 0.0169  Accuracy : 0.9956
Epoch : 154  Train Loss : 0.0050  Test Loss : 0.0168  Accuracy : 0.9956
Epoch : 156  Train Loss : 0.0048  Test Loss : 0.0167  Accuracy : 0.9956
Epoch : 158  Train Loss : 0.0047  Test Loss : 0.0166  Accuracy : 0.9956
Epoch : 160  Train Loss : 0.0045  Test Loss : 0.0166  Accuracy : 0.9956
Epoch : 162  Train Loss : 0.0044  Test Loss : 0.0165  Accuracy : 0.9956
Epoch : 164  Train Loss : 0.0043  Test Loss : 0.0165  Accuracy : 0.9956
Epoch : 166  Train Loss : 0.0041  Test Loss : 0.0164  Accuracy : 0.9956
Epoch : 168  Train Loss : 0.0040  Test Loss : 0.0165  Accuracy : 0.9956
Epoch : 170  Train Loss : 0.0039  Test Loss : 0.0165  Accuracy : 0.9956
Epoch : 172  Train Loss : 0.0038  Test Loss : 0.0165  Accuracy : 0.9956
Epoch : 174  Train Loss : 0.0037  Test Loss : 0.0164  Accuracy : 0.9956
Epoch : 176  Train Loss : 0.0035  Test Loss : 0.0164  Accuracy : 0.9956
Epoch : 178  Train Loss : 0.0034  Test Loss : 0.0164  Accuracy : 0.9956
Epoch : 180  Train Loss : 0.0033  Test Loss : 0.0165  Accuracy : 0.9956
Epoch : 182  Train Loss : 0.0033  Test Loss : 0.0164  Accuracy : 0.9956
Epoch : 184  Train Loss : 0.0032  Test Loss : 0.0164  Accuracy : 0.9956
Epoch : 186  Train Loss : 0.0031  Test Loss : 0.0164  Accuracy : 0.9956
Epoch : 188  Train Loss : 0.0030  Test Loss : 0.0164  Accuracy : 0.9956
Epoch : 190  Train Loss : 0.0029  Test Loss : 0.0164  Accuracy : 0.9956
Epoch : 192  Train Loss : 0.0028  Test Loss : 0.0164  Accuracy : 0.9956
Epoch : 194  Train Loss : 0.0027  Test Loss : 0.0165  Accuracy : 0.9956
Epoch : 196  Train Loss : 0.0027  Test Loss : 0.0165  Accuracy : 0.9956
Epoch : 198  Train Loss : 0.0026  Test Loss : 0.0165  Accuracy : 0.9956
Epoch : 200  Train Loss : 0.0025  Test Loss : 0.0165  Accuracy : 0.9956
Epoch : 202  Train Loss : 0.0025  Test Loss : 0.0166  Accuracy : 0.9950
Epoch : 204  Train Loss : 0.0024  Test Loss : 0.0166  Accuracy : 0.9950
Epoch : 206  Train Loss : 0.0023  Test Loss : 0.0166  Accuracy : 0.9950
Epoch : 208  Train Loss : 0.0023  Test Loss : 0.0166  Accuracy : 0.9950
Epoch : 210  Train Loss : 0.0022  Test Loss : 0.0166  Accuracy : 0.9950
Epoch : 212  Train Loss : 0.0022  Test Loss : 0.0166  Accuracy : 0.9950
Epoch : 214  Train Loss : 0.0021  Test Loss : 0.0166  Accuracy : 0.9950
Epoch : 216  Train Loss : 0.0021  Test Loss : 0.0167  Accuracy : 0.9950
Epoch : 218  Train Loss : 0.0020  Test Loss : 0.0166  Accuracy : 0.9950
Epoch : 220  Train Loss : 0.0020  Test Loss : 0.0166  Accuracy : 0.9950
Epoch : 222  Train Loss : 0.0019  Test Loss : 0.0167  Accuracy : 0.9950
Epoch : 224  Train Loss : 0.0019  Test Loss : 0.0168  Accuracy : 0.9950
Epoch : 226  Train Loss : 0.0018  Test Loss : 0.0168  Accuracy : 0.9950
Epoch : 228  Train Loss : 0.0018  Test Loss : 0.0168  Accuracy : 0.9950
Epoch : 230  Train Loss : 0.0017  Test Loss : 0.0169  Accuracy : 0.9950
Epoch : 232  Train Loss : 0.0017  Test Loss : 0.0169  Accuracy : 0.9956
Epoch : 234  Train Loss : 0.0017  Test Loss : 0.0170  Accuracy : 0.9956
Epoch : 236  Train Loss : 0.0016  Test Loss : 0.0170  Accuracy : 0.9956
Epoch : 238  Train Loss : 0.0016  Test Loss : 0.0171  Accuracy : 0.9956
Epoch : 240  Train Loss : 0.0016  Test Loss : 0.0171  Accuracy : 0.9956
Epoch : 242  Train Loss : 0.0015  Test Loss : 0.0172  Accuracy : 0.9956
Epoch : 244  Train Loss : 0.0015  Test Loss : 0.0173  Accuracy : 0.9956
Epoch : 246  Train Loss : 0.0015  Test Loss : 0.0173  Accuracy : 0.9956
Epoch : 248  Train Loss : 0.0014  Test Loss : 0.0174  Accuracy : 0.9956
Epoch : 250  Train Loss : 0.0014  Test Loss : 0.0174  Accuracy : 0.9956
Epoch : 252  Train Loss : 0.0014  Test Loss : 0.0175  Accuracy : 0.9956
Epoch : 254  Train Loss : 0.0014  Test Loss : 0.0175  Accuracy : 0.9956
Epoch : 256  Train Loss : 0.0013  Test Loss : 0.0176  Accuracy : 0.9956
Epoch : 258  Train Loss : 0.0013  Test Loss : 0.0176  Accuracy : 0.9956
Epoch : 260  Train Loss : 0.0013  Test Loss : 0.0177  Accuracy : 0.9956
Epoch : 262  Train Loss : 0.0013  Test Loss : 0.0177  Accuracy : 0.9956
Epoch : 264  Train Loss : 0.0012  Test Loss : 0.0177  Accuracy : 0.9956
Epoch : 266  Train Loss : 0.0012  Test Loss : 0.0178  Accuracy : 0.9956
Epoch : 268  Train Loss : 0.0012  Test Loss : 0.0179  Accuracy : 0.9956
Epoch : 270  Train Loss : 0.0012  Test Loss : 0.0180  Accuracy : 0.9956
Epoch : 272  Train Loss : 0.0011  Test Loss : 0.0180  Accuracy : 0.9956
Epoch : 274  Train Loss : 0.0011  Test Loss : 0.0180  Accuracy : 0.9956
Epoch : 276  Train Loss : 0.0011  Test Loss : 0.0181  Accuracy : 0.9956
Epoch : 278  Train Loss : 0.0011  Test Loss : 0.0182  Accuracy : 0.9956
Epoch : 280  Train Loss : 0.0011  Test Loss : 0.0183  Accuracy : 0.9956
Epoch : 282  Train Loss : 0.0010  Test Loss : 0.0183  Accuracy : 0.9956
Epoch : 284  Train Loss : 0.0010  Test Loss : 0.0183  Accuracy : 0.9956
Epoch : 286  Train Loss : 0.0010  Test Loss : 0.0184  Accuracy : 0.9956
Epoch : 288  Train Loss : 0.0010  Test Loss : 0.0185  Accuracy : 0.9956
Epoch : 290  Train Loss : 0.0010  Test Loss : 0.0185  Accuracy : 0.9956
Epoch : 292  Train Loss : 0.0010  Test Loss : 0.0186  Accuracy : 0.9956
Epoch : 294  Train Loss : 0.0009  Test Loss : 0.0187  Accuracy : 0.9956
Epoch : 296  Train Loss : 0.0009  Test Loss : 0.0187  Accuracy : 0.9956
Epoch : 298  Train Loss : 0.0009  Test Loss : 0.0188  Accuracy : 0.9950
Epoch : 300  Train Loss : 0.0009  Test Loss : 0.0189  Accuracy : 0.9950
Epoch : 302  Train Loss : 0.0009  Test Loss : 0.0189  Accuracy : 0.9956
Epoch : 304  Train Loss : 0.0009  Test Loss : 0.0190  Accuracy : 0.9950
Epoch : 306  Train Loss : 0.0008  Test Loss : 0.0190  Accuracy : 0.9950
Epoch : 308  Train Loss : 0.0008  Test Loss : 0.0191  Accuracy : 0.9950
Epoch : 310  Train Loss : 0.0008  Test Loss : 0.0191  Accuracy : 0.9950
Epoch : 312  Train Loss : 0.0008  Test Loss : 0.0192  Accuracy : 0.9950
Epoch : 314  Train Loss : 0.0008  Test Loss : 0.0193  Accuracy : 0.9950
Epoch : 316  Train Loss : 0.0008  Test Loss : 0.0194  Accuracy : 0.9950
Epoch : 318  Train Loss : 0.0008  Test Loss : 0.0195  Accuracy : 0.9950
Epoch : 320  Train Loss : 0.0008  Test Loss : 0.0195  Accuracy : 0.9950
Epoch : 322  Train Loss : 0.0007  Test Loss : 0.0196  Accuracy : 0.9950
Epoch : 324  Train Loss : 0.0007  Test Loss : 0.0196  Accuracy : 0.9950
Epoch : 326  Train Loss : 0.0007  Test Loss : 0.0197  Accuracy : 0.9950
Epoch : 328  Train Loss : 0.0007  Test Loss : 0.0198  Accuracy : 0.9950
Epoch : 330  Train Loss : 0.0007  Test Loss : 0.0198  Accuracy : 0.9950
Epoch : 332  Train Loss : 0.0007  Test Loss : 0.0199  Accuracy : 0.9950
Epoch : 334  Train Loss : 0.0007  Test Loss : 0.0200  Accuracy : 0.9956
Epoch : 336  Train Loss : 0.0007  Test Loss : 0.0201  Accuracy : 0.9956
Epoch : 338  Train Loss : 0.0006  Test Loss : 0.0201  Accuracy : 0.9956
Epoch : 340  Train Loss : 0.0006  Test Loss : 0.0202  Accuracy : 0.9956
Epoch : 342  Train Loss : 0.0006  Test Loss : 0.0202  Accuracy : 0.9956
Epoch : 344  Train Loss : 0.0006  Test Loss : 0.0203  Accuracy : 0.9956
Epoch : 346  Train Loss : 0.0006  Test Loss : 0.0204  Accuracy : 0.9956
Epoch : 348  Train Loss : 0.0006  Test Loss : 0.0204  Accuracy : 0.9956
Epoch : 350  Train Loss : 0.0006  Test Loss : 0.0204  Accuracy : 0.9956
Epoch : 352  Train Loss : 0.0006  Test Loss : 0.0205  Accuracy : 0.9956
Epoch : 354  Train Loss : 0.0006  Test Loss : 0.0206  Accuracy : 0.9956
Epoch : 356  Train Loss : 0.0006  Test Loss : 0.0206  Accuracy : 0.9956
Epoch : 358  Train Loss : 0.0006  Test Loss : 0.0207  Accuracy : 0.9956
Epoch : 360  Train Loss : 0.0005  Test Loss : 0.0207  Accuracy : 0.9956
Epoch : 362  Train Loss : 0.0005  Test Loss : 0.0208  Accuracy : 0.9956
Epoch : 364  Train Loss : 0.0005  Test Loss : 0.0209  Accuracy : 0.9956
Epoch : 366  Train Loss : 0.0005  Test Loss : 0.0209  Accuracy : 0.9956
Epoch : 368  Train Loss : 0.0005  Test Loss : 0.0210  Accuracy : 0.9956
Epoch : 370  Train Loss : 0.0005  Test Loss : 0.0210  Accuracy : 0.9956
Epoch : 372  Train Loss : 0.0005  Test Loss : 0.0211  Accuracy : 0.9956
Epoch : 374  Train Loss : 0.0005  Test Loss : 0.0211  Accuracy : 0.9956
Epoch : 376  Train Loss : 0.0005  Test Loss : 0.0212  Accuracy : 0.9956
Epoch : 378  Train Loss : 0.0005  Test Loss : 0.0212  Accuracy : 0.9956
Epoch : 380  Train Loss : 0.0005  Test Loss : 0.0213  Accuracy : 0.9956
Epoch : 382  Train Loss : 0.0005  Test Loss : 0.0213  Accuracy : 0.9956
Epoch : 384  Train Loss : 0.0005  Test Loss : 0.0214  Accuracy : 0.9956
Epoch : 386  Train Loss : 0.0005  Test Loss : 0.0214  Accuracy : 0.9956
Epoch : 388  Train Loss : 0.0004  Test Loss : 0.0214  Accuracy : 0.9956
Epoch : 390  Train Loss : 0.0004  Test Loss : 0.0215  Accuracy : 0.9956
Epoch : 392  Train Loss : 0.0004  Test Loss : 0.0216  Accuracy : 0.9956
Epoch : 394  Train Loss : 0.0004  Test Loss : 0.0217  Accuracy : 0.9956
Epoch : 396  Train Loss : 0.0004  Test Loss : 0.0217  Accuracy : 0.9956
Epoch : 398  Train Loss : 0.0004  Test Loss : 0.0218  Accuracy : 0.9956
Epoch : 400  Train Loss : 0.0004  Test Loss : 0.0218  Accuracy : 0.9956
Epoch : 402  Train Loss : 0.0004  Test Loss : 0.0218  Accuracy : 0.9956
Epoch : 404  Train Loss : 0.0004  Test Loss : 0.0219  Accuracy : 0.9956
Epoch : 406  Train Loss : 0.0004  Test Loss : 0.0220  Accuracy : 0.9956
Epoch : 408  Train Loss : 0.0004  Test Loss : 0.0220  Accuracy : 0.9956
Epoch : 410  Train Loss : 0.0004  Test Loss : 0.0220  Accuracy : 0.9956
Epoch : 412  Train Loss : 0.0004  Test Loss : 0.0221  Accuracy : 0.9956
Epoch : 414  Train Loss : 0.0004  Test Loss : 0.0222  Accuracy : 0.9956
Epoch : 416  Train Loss : 0.0004  Test Loss : 0.0222  Accuracy : 0.9956
Epoch : 418  Train Loss : 0.0004  Test Loss : 0.0222  Accuracy : 0.9956
Epoch : 420  Train Loss : 0.0004  Test Loss : 0.0223  Accuracy : 0.9956
Epoch : 422  Train Loss : 0.0004  Test Loss : 0.0223  Accuracy : 0.9956
Epoch : 424  Train Loss : 0.0004  Test Loss : 0.0224  Accuracy : 0.9956
Epoch : 426  Train Loss : 0.0003  Test Loss : 0.0224  Accuracy : 0.9956
Epoch : 428  Train Loss : 0.0003  Test Loss : 0.0225  Accuracy : 0.9956
Epoch : 430  Train Loss : 0.0003  Test Loss : 0.0225  Accuracy : 0.9956
Epoch : 432  Train Loss : 0.0003  Test Loss : 0.0225  Accuracy : 0.9956
Epoch : 434  Train Loss : 0.0003  Test Loss : 0.0226  Accuracy : 0.9956
Epoch : 436  Train Loss : 0.0003  Test Loss : 0.0226  Accuracy : 0.9956
Epoch : 438  Train Loss : 0.0003  Test Loss : 0.0226  Accuracy : 0.9956
Epoch : 440  Train Loss : 0.0003  Test Loss : 0.0226  Accuracy : 0.9956
Epoch : 442  Train Loss : 0.0003  Test Loss : 0.0226  Accuracy : 0.9956
Epoch : 444  Train Loss : 0.0003  Test Loss : 0.0227  Accuracy : 0.9956
Epoch : 446  Train Loss : 0.0003  Test Loss : 0.0227  Accuracy : 0.9950
Epoch : 448  Train Loss : 0.0003  Test Loss : 0.0227  Accuracy : 0.9950
Epoch : 450  Train Loss : 0.0003  Test Loss : 0.0227  Accuracy : 0.9950
Epoch : 452  Train Loss : 0.0003  Test Loss : 0.0227  Accuracy : 0.9950
Epoch : 454  Train Loss : 0.0003  Test Loss : 0.0227  Accuracy : 0.9950
Epoch : 456  Train Loss : 0.0003  Test Loss : 0.0227  Accuracy : 0.9950
Epoch : 458  Train Loss : 0.0003  Test Loss : 0.0228  Accuracy : 0.9950
Epoch : 460  Train Loss : 0.0003  Test Loss : 0.0228  Accuracy : 0.9950
Epoch : 462  Train Loss : 0.0003  Test Loss : 0.0229  Accuracy : 0.9950
Epoch : 464  Train Loss : 0.0003  Test Loss : 0.0229  Accuracy : 0.9950
Epoch : 466  Train Loss : 0.0003  Test Loss : 0.0229  Accuracy : 0.9950
Epoch : 468  Train Loss : 0.0003  Test Loss : 0.0230  Accuracy : 0.9950
Epoch : 470  Train Loss : 0.0003  Test Loss : 0.0230  Accuracy : 0.9950
Epoch : 472  Train Loss : 0.0003  Test Loss : 0.0230  Accuracy : 0.9950
Epoch : 474  Train Loss : 0.0002  Test Loss : 0.0230  Accuracy : 0.9950
Epoch : 476  Train Loss : 0.0002  Test Loss : 0.0231  Accuracy : 0.9950
Epoch : 478  Train Loss : 0.0002  Test Loss : 0.0231  Accuracy : 0.9950
Epoch : 480  Train Loss : 0.0002  Test Loss : 0.0232  Accuracy : 0.9950
Epoch : 482  Train Loss : 0.0002  Test Loss : 0.0232  Accuracy : 0.9950
Epoch : 484  Train Loss : 0.0002  Test Loss : 0.0232  Accuracy : 0.9950
Epoch : 486  Train Loss : 0.0002  Test Loss : 0.0232  Accuracy : 0.9950
Epoch : 488  Train Loss : 0.0002  Test Loss : 0.0233  Accuracy : 0.9950
Epoch : 490  Train Loss : 0.0002  Test Loss : 0.0233  Accuracy : 0.9950
Epoch : 492  Train Loss : 0.0002  Test Loss : 0.0233  Accuracy : 0.9950
Epoch : 494  Train Loss : 0.0002  Test Loss : 0.0234  Accuracy : 0.9950
Epoch : 496  Train Loss : 0.0002  Test Loss : 0.0234  Accuracy : 0.9950
Epoch : 498  Train Loss : 0.0002  Test Loss : 0.0235  Accuracy : 0.9950

In [114]:
torch.save(m2.state_dict(), "saved_models/m2.pth")

In [115]:
class MLP(nn.Module):
    
    def __init__(self):
        super().__init__()
        
        self.layer_stack = nn.Sequential(
            
            nn.Linear(4, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            
            nn.Linear(64, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            
            nn.Linear(64, 6)
        )
        
    def forward(self, x):
        
        return self.layer_stack(x)


m3 = MLP()

In [116]:
op1 = optim.Adam(m3.parameters() , lr = 0.001)

In [117]:
train_step(m3 ,500 , acc , loss , op1 , x2_train , y2_train , x2_test , y2_test)

  0%|          | 0/500 [00:00<?, ?it/s]

Epoch : 0  Train Loss : 0.6965  Test Loss : 0.6883  Accuracy : 0.5700
Epoch : 2  Train Loss : 0.6870  Test Loss : 0.6796  Accuracy : 0.6211
Epoch : 4  Train Loss : 0.6776  Test Loss : 0.6711  Accuracy : 0.6578
Epoch : 6  Train Loss : 0.6685  Test Loss : 0.6626  Accuracy : 0.7050
Epoch : 8  Train Loss : 0.6608  Test Loss : 0.6540  Accuracy : 0.7372
Epoch : 10  Train Loss : 0.6523  Test Loss : 0.6450  Accuracy : 0.7739
Epoch : 12  Train Loss : 0.6413  Test Loss : 0.6355  Accuracy : 0.8106
Epoch : 14  Train Loss : 0.6320  Test Loss : 0.6255  Accuracy : 0.8456
Epoch : 16  Train Loss : 0.6211  Test Loss : 0.6148  Accuracy : 0.8694
Epoch : 18  Train Loss : 0.6089  Test Loss : 0.6033  Accuracy : 0.8922
Epoch : 20  Train Loss : 0.5962  Test Loss : 0.5911  Accuracy : 0.9100
Epoch : 22  Train Loss : 0.5840  Test Loss : 0.5780  Accuracy : 0.9178
Epoch : 24  Train Loss : 0.5738  Test Loss : 0.5641  Accuracy : 0.9228
Epoch : 26  Train Loss : 0.5566  Test Loss : 0.5493  Accuracy : 0.9306
Epoch : 28  Train Loss : 0.5436  Test Loss : 0.5338  Accuracy : 0.9333
Epoch : 30  Train Loss : 0.5247  Test Loss : 0.5176  Accuracy : 0.9372
Epoch : 32  Train Loss : 0.5103  Test Loss : 0.5007  Accuracy : 0.9428
Epoch : 34  Train Loss : 0.4924  Test Loss : 0.4832  Accuracy : 0.9444
Epoch : 36  Train Loss : 0.4730  Test Loss : 0.4651  Accuracy : 0.9450
Epoch : 38  Train Loss : 0.4580  Test Loss : 0.4467  Accuracy : 0.9489
Epoch : 40  Train Loss : 0.4398  Test Loss : 0.4280  Accuracy : 0.9533
Epoch : 42  Train Loss : 0.4210  Test Loss : 0.4092  Accuracy : 0.9556
Epoch : 44  Train Loss : 0.4026  Test Loss : 0.3903  Accuracy : 0.9589
Epoch : 46  Train Loss : 0.3835  Test Loss : 0.3716  Accuracy : 0.9611
Epoch : 48  Train Loss : 0.3654  Test Loss : 0.3530  Accuracy : 0.9639
Epoch : 50  Train Loss : 0.3496  Test Loss : 0.3348  Accuracy : 0.9672
Epoch : 52  Train Loss : 0.3353  Test Loss : 0.3171  Accuracy : 0.9694
Epoch : 54  Train Loss : 0.3202  Test Loss : 0.3000  Accuracy : 0.9722
Epoch : 56  Train Loss : 0.3000  Test Loss : 0.2836  Accuracy : 0.9733
Epoch : 58  Train Loss : 0.2884  Test Loss : 0.2681  Accuracy : 0.9756
Epoch : 60  Train Loss : 0.2721  Test Loss : 0.2534  Accuracy : 0.9783
Epoch : 62  Train Loss : 0.2538  Test Loss : 0.2396  Accuracy : 0.9800
Epoch : 64  Train Loss : 0.2480  Test Loss : 0.2266  Accuracy : 0.9817
Epoch : 66  Train Loss : 0.2300  Test Loss : 0.2145  Accuracy : 0.9822
Epoch : 68  Train Loss : 0.2245  Test Loss : 0.2033  Accuracy : 0.9833
Epoch : 70  Train Loss : 0.2158  Test Loss : 0.1930  Accuracy : 0.9850
Epoch : 72  Train Loss : 0.2017  Test Loss : 0.1834  Accuracy : 0.9856
Epoch : 74  Train Loss : 0.1949  Test Loss : 0.1746  Accuracy : 0.9856
Epoch : 76  Train Loss : 0.1843  Test Loss : 0.1665  Accuracy : 0.9867
Epoch : 78  Train Loss : 0.1826  Test Loss : 0.1592  Accuracy : 0.9867
Epoch : 80  Train Loss : 0.1781  Test Loss : 0.1525  Accuracy : 0.9867
Epoch : 82  Train Loss : 0.1650  Test Loss : 0.1464  Accuracy : 0.9872
Epoch : 84  Train Loss : 0.1649  Test Loss : 0.1410  Accuracy : 0.9878
Epoch : 86  Train Loss : 0.1575  Test Loss : 0.1360  Accuracy : 0.9872
Epoch : 88  Train Loss : 0.1489  Test Loss : 0.1313  Accuracy : 0.9883
Epoch : 90  Train Loss : 0.1473  Test Loss : 0.1268  Accuracy : 0.9883
Epoch : 92  Train Loss : 0.1410  Test Loss : 0.1227  Accuracy : 0.9889
Epoch : 94  Train Loss : 0.1371  Test Loss : 0.1190  Accuracy : 0.9894
Epoch : 96  Train Loss : 0.1341  Test Loss : 0.1154  Accuracy : 0.9900
Epoch : 98  Train Loss : 0.1317  Test Loss : 0.1121  Accuracy : 0.9906
Epoch : 100  Train Loss : 0.1239  Test Loss : 0.1089  Accuracy : 0.9917
Epoch : 102  Train Loss : 0.1224  Test Loss : 0.1060  Accuracy : 0.9911
Epoch : 104  Train Loss : 0.1283  Test Loss : 0.1033  Accuracy : 0.9911
Epoch : 106  Train Loss : 0.1256  Test Loss : 0.1007  Accuracy : 0.9917
Epoch : 108  Train Loss : 0.1142  Test Loss : 0.0983  Accuracy : 0.9917
Epoch : 110  Train Loss : 0.1193  Test Loss : 0.0960  Accuracy : 0.9917
Epoch : 112  Train Loss : 0.1138  Test Loss : 0.0939  Accuracy : 0.9911
Epoch : 114  Train Loss : 0.1182  Test Loss : 0.0920  Accuracy : 0.9911
Epoch : 116  Train Loss : 0.1138  Test Loss : 0.0902  Accuracy : 0.9911
Epoch : 118  Train Loss : 0.1124  Test Loss : 0.0884  Accuracy : 0.9906
Epoch : 120  Train Loss : 0.1127  Test Loss : 0.0867  Accuracy : 0.9911
Epoch : 122  Train Loss : 0.1071  Test Loss : 0.0854  Accuracy : 0.9917
Epoch : 124  Train Loss : 0.1055  Test Loss : 0.0840  Accuracy : 0.9917
Epoch : 126  Train Loss : 0.1070  Test Loss : 0.0826  Accuracy : 0.9917
Epoch : 128  Train Loss : 0.1039  Test Loss : 0.0812  Accuracy : 0.9922
Epoch : 130  Train Loss : 0.1022  Test Loss : 0.0798  Accuracy : 0.9917
Epoch : 132  Train Loss : 0.1007  Test Loss : 0.0784  Accuracy : 0.9922
Epoch : 134  Train Loss : 0.0985  Test Loss : 0.0770  Accuracy : 0.9911
Epoch : 136  Train Loss : 0.0989  Test Loss : 0.0758  Accuracy : 0.9911
Epoch : 138  Train Loss : 0.1009  Test Loss : 0.0746  Accuracy : 0.9917
Epoch : 140  Train Loss : 0.0995  Test Loss : 0.0733  Accuracy : 0.9917
Epoch : 142  Train Loss : 0.0944  Test Loss : 0.0723  Accuracy : 0.9917
Epoch : 144  Train Loss : 0.0931  Test Loss : 0.0714  Accuracy : 0.9917
Epoch : 146  Train Loss : 0.0926  Test Loss : 0.0706  Accuracy : 0.9917
Epoch : 148  Train Loss : 0.0854  Test Loss : 0.0697  Accuracy : 0.9917
Epoch : 150  Train Loss : 0.0995  Test Loss : 0.0689  Accuracy : 0.9933
Epoch : 152  Train Loss : 0.1043  Test Loss : 0.0680  Accuracy : 0.9933
Epoch : 154  Train Loss : 0.0911  Test Loss : 0.0672  Accuracy : 0.9939
Epoch : 156  Train Loss : 0.0862  Test Loss : 0.0663  Accuracy : 0.9944
Epoch : 158  Train Loss : 0.0914  Test Loss : 0.0651  Accuracy : 0.9939
Epoch : 160  Train Loss : 0.0923  Test Loss : 0.0642  Accuracy : 0.9933
Epoch : 162  Train Loss : 0.0927  Test Loss : 0.0634  Accuracy : 0.9928
Epoch : 164  Train Loss : 0.0847  Test Loss : 0.0627  Accuracy : 0.9928
Epoch : 166  Train Loss : 0.0881  Test Loss : 0.0620  Accuracy : 0.9928
Epoch : 168  Train Loss : 0.0876  Test Loss : 0.0614  Accuracy : 0.9928
Epoch : 170  Train Loss : 0.0767  Test Loss : 0.0608  Accuracy : 0.9928
Epoch : 172  Train Loss : 0.0824  Test Loss : 0.0603  Accuracy : 0.9928
Epoch : 174  Train Loss : 0.0797  Test Loss : 0.0597  Accuracy : 0.9928
Epoch : 176  Train Loss : 0.0773  Test Loss : 0.0592  Accuracy : 0.9922
Epoch : 178  Train Loss : 0.0872  Test Loss : 0.0588  Accuracy : 0.9922
Epoch : 180  Train Loss : 0.0871  Test Loss : 0.0582  Accuracy : 0.9922
Epoch : 182  Train Loss : 0.0857  Test Loss : 0.0575  Accuracy : 0.9922
Epoch : 184  Train Loss : 0.0859  Test Loss : 0.0568  Accuracy : 0.9922
Epoch : 186  Train Loss : 0.0731  Test Loss : 0.0563  Accuracy : 0.9922
Epoch : 188  Train Loss : 0.0778  Test Loss : 0.0557  Accuracy : 0.9922
Epoch : 190  Train Loss : 0.0782  Test Loss : 0.0550  Accuracy : 0.9922
Epoch : 192  Train Loss : 0.0888  Test Loss : 0.0544  Accuracy : 0.9922
Epoch : 194  Train Loss : 0.0766  Test Loss : 0.0538  Accuracy : 0.9922
Epoch : 196  Train Loss : 0.0772  Test Loss : 0.0532  Accuracy : 0.9922
Epoch : 198  Train Loss : 0.0747  Test Loss : 0.0528  Accuracy : 0.9928
Epoch : 200  Train Loss : 0.0827  Test Loss : 0.0525  Accuracy : 0.9928
Epoch : 202  Train Loss : 0.0800  Test Loss : 0.0522  Accuracy : 0.9928
Epoch : 204  Train Loss : 0.0786  Test Loss : 0.0519  Accuracy : 0.9928
Epoch : 206  Train Loss : 0.0814  Test Loss : 0.0515  Accuracy : 0.9928
Epoch : 208  Train Loss : 0.0780  Test Loss : 0.0511  Accuracy : 0.9928
Epoch : 210  Train Loss : 0.0803  Test Loss : 0.0505  Accuracy : 0.9928
Epoch : 212  Train Loss : 0.0795  Test Loss : 0.0500  Accuracy : 0.9928
Epoch : 214  Train Loss : 0.0726  Test Loss : 0.0497  Accuracy : 0.9928
Epoch : 216  Train Loss : 0.0772  Test Loss : 0.0494  Accuracy : 0.9933
Epoch : 218  Train Loss : 0.0681  Test Loss : 0.0490  Accuracy : 0.9933
Epoch : 220  Train Loss : 0.0699  Test Loss : 0.0486  Accuracy : 0.9933
Epoch : 222  Train Loss : 0.0736  Test Loss : 0.0483  Accuracy : 0.9928
Epoch : 224  Train Loss : 0.0699  Test Loss : 0.0478  Accuracy : 0.9928
Epoch : 226  Train Loss : 0.0710  Test Loss : 0.0474  Accuracy : 0.9922
Epoch : 228  Train Loss : 0.0670  Test Loss : 0.0472  Accuracy : 0.9922
Epoch : 230  Train Loss : 0.0715  Test Loss : 0.0471  Accuracy : 0.9928
Epoch : 232  Train Loss : 0.0736  Test Loss : 0.0467  Accuracy : 0.9922
Epoch : 234  Train Loss : 0.0719  Test Loss : 0.0465  Accuracy : 0.9933
Epoch : 236  Train Loss : 0.0677  Test Loss : 0.0460  Accuracy : 0.9933
Epoch : 238  Train Loss : 0.0715  Test Loss : 0.0456  Accuracy : 0.9933
Epoch : 240  Train Loss : 0.0692  Test Loss : 0.0452  Accuracy : 0.9933
Epoch : 242  Train Loss : 0.0678  Test Loss : 0.0447  Accuracy : 0.9928
Epoch : 244  Train Loss : 0.0676  Test Loss : 0.0444  Accuracy : 0.9928
Epoch : 246  Train Loss : 0.0708  Test Loss : 0.0443  Accuracy : 0.9928
Epoch : 248  Train Loss : 0.0783  Test Loss : 0.0443  Accuracy : 0.9922
Epoch : 250  Train Loss : 0.0726  Test Loss : 0.0441  Accuracy : 0.9922
Epoch : 252  Train Loss : 0.0712  Test Loss : 0.0439  Accuracy : 0.9939
Epoch : 254  Train Loss : 0.0660  Test Loss : 0.0434  Accuracy : 0.9933
Epoch : 256  Train Loss : 0.0667  Test Loss : 0.0428  Accuracy : 0.9933
Epoch : 258  Train Loss : 0.0649  Test Loss : 0.0423  Accuracy : 0.9928
Epoch : 260  Train Loss : 0.0746  Test Loss : 0.0417  Accuracy : 0.9933
Epoch : 262  Train Loss : 0.0685  Test Loss : 0.0413  Accuracy : 0.9933
Epoch : 264  Train Loss : 0.0703  Test Loss : 0.0409  Accuracy : 0.9933
Epoch : 266  Train Loss : 0.0730  Test Loss : 0.0407  Accuracy : 0.9933
Epoch : 268  Train Loss : 0.0640  Test Loss : 0.0406  Accuracy : 0.9933
Epoch : 270  Train Loss : 0.0674  Test Loss : 0.0405  Accuracy : 0.9933
Epoch : 272  Train Loss : 0.0653  Test Loss : 0.0405  Accuracy : 0.9933
Epoch : 274  Train Loss : 0.0631  Test Loss : 0.0404  Accuracy : 0.9933
Epoch : 276  Train Loss : 0.0658  Test Loss : 0.0404  Accuracy : 0.9922
Epoch : 278  Train Loss : 0.0648  Test Loss : 0.0404  Accuracy : 0.9917
Epoch : 280  Train Loss : 0.0656  Test Loss : 0.0404  Accuracy : 0.9911
Epoch : 282  Train Loss : 0.0642  Test Loss : 0.0404  Accuracy : 0.9922
Epoch : 284  Train Loss : 0.0653  Test Loss : 0.0403  Accuracy : 0.9928
Epoch : 286  Train Loss : 0.0634  Test Loss : 0.0401  Accuracy : 0.9922
Epoch : 288  Train Loss : 0.0643  Test Loss : 0.0399  Accuracy : 0.9917
Epoch : 290  Train Loss : 0.0638  Test Loss : 0.0399  Accuracy : 0.9922
Epoch : 292  Train Loss : 0.0657  Test Loss : 0.0397  Accuracy : 0.9922
Epoch : 294  Train Loss : 0.0612  Test Loss : 0.0392  Accuracy : 0.9928
Epoch : 296  Train Loss : 0.0598  Test Loss : 0.0387  Accuracy : 0.9928
Epoch : 298  Train Loss : 0.0597  Test Loss : 0.0383  Accuracy : 0.9922
Epoch : 300  Train Loss : 0.0669  Test Loss : 0.0378  Accuracy : 0.9922
Epoch : 302  Train Loss : 0.0649  Test Loss : 0.0375  Accuracy : 0.9922
Epoch : 304  Train Loss : 0.0552  Test Loss : 0.0373  Accuracy : 0.9928
Epoch : 306  Train Loss : 0.0643  Test Loss : 0.0373  Accuracy : 0.9928
Epoch : 308  Train Loss : 0.0618  Test Loss : 0.0372  Accuracy : 0.9917
Epoch : 310  Train Loss : 0.0637  Test Loss : 0.0371  Accuracy : 0.9917
Epoch : 312  Train Loss : 0.0632  Test Loss : 0.0370  Accuracy : 0.9922
Epoch : 314  Train Loss : 0.0583  Test Loss : 0.0368  Accuracy : 0.9928
Epoch : 316  Train Loss : 0.0543  Test Loss : 0.0368  Accuracy : 0.9928
Epoch : 318  Train Loss : 0.0653  Test Loss : 0.0368  Accuracy : 0.9933
Epoch : 320  Train Loss : 0.0557  Test Loss : 0.0365  Accuracy : 0.9939
Epoch : 322  Train Loss : 0.0599  Test Loss : 0.0362  Accuracy : 0.9939
Epoch : 324  Train Loss : 0.0658  Test Loss : 0.0360  Accuracy : 0.9933
Epoch : 326  Train Loss : 0.0626  Test Loss : 0.0357  Accuracy : 0.9933
Epoch : 328  Train Loss : 0.0565  Test Loss : 0.0355  Accuracy : 0.9939
Epoch : 330  Train Loss : 0.0611  Test Loss : 0.0353  Accuracy : 0.9939
Epoch : 332  Train Loss : 0.0644  Test Loss : 0.0352  Accuracy : 0.9933
Epoch : 334  Train Loss : 0.0618  Test Loss : 0.0351  Accuracy : 0.9933
Epoch : 336  Train Loss : 0.0570  Test Loss : 0.0349  Accuracy : 0.9933
Epoch : 338  Train Loss : 0.0512  Test Loss : 0.0347  Accuracy : 0.9933
Epoch : 340  Train Loss : 0.0603  Test Loss : 0.0343  Accuracy : 0.9939
Epoch : 342  Train Loss : 0.0648  Test Loss : 0.0340  Accuracy : 0.9944
Epoch : 344  Train Loss : 0.0622  Test Loss : 0.0337  Accuracy : 0.9939
Epoch : 346  Train Loss : 0.0677  Test Loss : 0.0334  Accuracy : 0.9944
Epoch : 348  Train Loss : 0.0660  Test Loss : 0.0333  Accuracy : 0.9944
Epoch : 350  Train Loss : 0.0544  Test Loss : 0.0333  Accuracy : 0.9944
Epoch : 352  Train Loss : 0.0550  Test Loss : 0.0331  Accuracy : 0.9944
Epoch : 354  Train Loss : 0.0525  Test Loss : 0.0329  Accuracy : 0.9944
Epoch : 356  Train Loss : 0.0565  Test Loss : 0.0328  Accuracy : 0.9944
Epoch : 358  Train Loss : 0.0567  Test Loss : 0.0328  Accuracy : 0.9944
Epoch : 360  Train Loss : 0.0563  Test Loss : 0.0329  Accuracy : 0.9944
Epoch : 362  Train Loss : 0.0507  Test Loss : 0.0330  Accuracy : 0.9944
Epoch : 364  Train Loss : 0.0562  Test Loss : 0.0330  Accuracy : 0.9944
Epoch : 366  Train Loss : 0.0567  Test Loss : 0.0331  Accuracy : 0.9944
Epoch : 368  Train Loss : 0.0586  Test Loss : 0.0331  Accuracy : 0.9944
Epoch : 370  Train Loss : 0.0627  Test Loss : 0.0328  Accuracy : 0.9944
Epoch : 372  Train Loss : 0.0578  Test Loss : 0.0324  Accuracy : 0.9944
Epoch : 374  Train Loss : 0.0587  Test Loss : 0.0319  Accuracy : 0.9944
Epoch : 376  Train Loss : 0.0539  Test Loss : 0.0315  Accuracy : 0.9950
Epoch : 378  Train Loss : 0.0526  Test Loss : 0.0312  Accuracy : 0.9939
Epoch : 380  Train Loss : 0.0553  Test Loss : 0.0311  Accuracy : 0.9933
Epoch : 382  Train Loss : 0.0545  Test Loss : 0.0310  Accuracy : 0.9944
Epoch : 384  Train Loss : 0.0612  Test Loss : 0.0311  Accuracy : 0.9944
Epoch : 386  Train Loss : 0.0560  Test Loss : 0.0314  Accuracy : 0.9944
Epoch : 388  Train Loss : 0.0566  Test Loss : 0.0318  Accuracy : 0.9944
Epoch : 390  Train Loss : 0.0599  Test Loss : 0.0321  Accuracy : 0.9944
Epoch : 392  Train Loss : 0.0595  Test Loss : 0.0319  Accuracy : 0.9944
Epoch : 394  Train Loss : 0.0608  Test Loss : 0.0318  Accuracy : 0.9944
Epoch : 396  Train Loss : 0.0568  Test Loss : 0.0315  Accuracy : 0.9944
Epoch : 398  Train Loss : 0.0484  Test Loss : 0.0312  Accuracy : 0.9950
Epoch : 400  Train Loss : 0.0566  Test Loss : 0.0310  Accuracy : 0.9950
Epoch : 402  Train Loss : 0.0554  Test Loss : 0.0308  Accuracy : 0.9944
Epoch : 404  Train Loss : 0.0497  Test Loss : 0.0306  Accuracy : 0.9944
Epoch : 406  Train Loss : 0.0501  Test Loss : 0.0302  Accuracy : 0.9950
Epoch : 408  Train Loss : 0.0526  Test Loss : 0.0299  Accuracy : 0.9956
Epoch : 410  Train Loss : 0.0516  Test Loss : 0.0298  Accuracy : 0.9956
Epoch : 412  Train Loss : 0.0481  Test Loss : 0.0298  Accuracy : 0.9950
Epoch : 414  Train Loss : 0.0570  Test Loss : 0.0299  Accuracy : 0.9950
Epoch : 416  Train Loss : 0.0551  Test Loss : 0.0299  Accuracy : 0.9944
Epoch : 418  Train Loss : 0.0619  Test Loss : 0.0301  Accuracy : 0.9944
Epoch : 420  Train Loss : 0.0628  Test Loss : 0.0301  Accuracy : 0.9933
Epoch : 422  Train Loss : 0.0503  Test Loss : 0.0301  Accuracy : 0.9933
Epoch : 424  Train Loss : 0.0451  Test Loss : 0.0300  Accuracy : 0.9933
Epoch : 426  Train Loss : 0.0508  Test Loss : 0.0298  Accuracy : 0.9928
Epoch : 428  Train Loss : 0.0532  Test Loss : 0.0293  Accuracy : 0.9939
Epoch : 430  Train Loss : 0.0487  Test Loss : 0.0289  Accuracy : 0.9939
Epoch : 432  Train Loss : 0.0582  Test Loss : 0.0286  Accuracy : 0.9944
Epoch : 434  Train Loss : 0.0518  Test Loss : 0.0286  Accuracy : 0.9950
Epoch : 436  Train Loss : 0.0468  Test Loss : 0.0286  Accuracy : 0.9944
Epoch : 438  Train Loss : 0.0425  Test Loss : 0.0286  Accuracy : 0.9944
Epoch : 440  Train Loss : 0.0520  Test Loss : 0.0286  Accuracy : 0.9950
Epoch : 442  Train Loss : 0.0547  Test Loss : 0.0285  Accuracy : 0.9944
Epoch : 444  Train Loss : 0.0530  Test Loss : 0.0282  Accuracy : 0.9933
Epoch : 446  Train Loss : 0.0474  Test Loss : 0.0280  Accuracy : 0.9939
Epoch : 448  Train Loss : 0.0505  Test Loss : 0.0279  Accuracy : 0.9944
Epoch : 450  Train Loss : 0.0511  Test Loss : 0.0279  Accuracy : 0.9944
Epoch : 452  Train Loss : 0.0520  Test Loss : 0.0278  Accuracy : 0.9944
Epoch : 454  Train Loss : 0.0544  Test Loss : 0.0278  Accuracy : 0.9944
Epoch : 456  Train Loss : 0.0523  Test Loss : 0.0277  Accuracy : 0.9944
Epoch : 458  Train Loss : 0.0468  Test Loss : 0.0277  Accuracy : 0.9944
Epoch : 460  Train Loss : 0.0524  Test Loss : 0.0277  Accuracy : 0.9939
Epoch : 462  Train Loss : 0.0475  Test Loss : 0.0275  Accuracy : 0.9944
Epoch : 464  Train Loss : 0.0503  Test Loss : 0.0273  Accuracy : 0.9944
Epoch : 466  Train Loss : 0.0517  Test Loss : 0.0271  Accuracy : 0.9956
Epoch : 468  Train Loss : 0.0460  Test Loss : 0.0268  Accuracy : 0.9956
Epoch : 470  Train Loss : 0.0462  Test Loss : 0.0267  Accuracy : 0.9956
Epoch : 472  Train Loss : 0.0482  Test Loss : 0.0266  Accuracy : 0.9956
Epoch : 474  Train Loss : 0.0482  Test Loss : 0.0267  Accuracy : 0.9956
Epoch : 476  Train Loss : 0.0432  Test Loss : 0.0268  Accuracy : 0.9956
Epoch : 478  Train Loss : 0.0432  Test Loss : 0.0271  Accuracy : 0.9944
Epoch : 480  Train Loss : 0.0508  Test Loss : 0.0274  Accuracy : 0.9956
Epoch : 482  Train Loss : 0.0508  Test Loss : 0.0277  Accuracy : 0.9956
Epoch : 484  Train Loss : 0.0502  Test Loss : 0.0276  Accuracy : 0.9956
Epoch : 486  Train Loss : 0.0486  Test Loss : 0.0275  Accuracy : 0.9956
Epoch : 488  Train Loss : 0.0439  Test Loss : 0.0271  Accuracy : 0.9944
Epoch : 490  Train Loss : 0.0481  Test Loss : 0.0268  Accuracy : 0.9944
Epoch : 492  Train Loss : 0.0433  Test Loss : 0.0264  Accuracy : 0.9956
Epoch : 494  Train Loss : 0.0478  Test Loss : 0.0263  Accuracy : 0.9956
Epoch : 496  Train Loss : 0.0501  Test Loss : 0.0263  Accuracy : 0.9961
Epoch : 498  Train Loss : 0.0474  Test Loss : 0.0264  Accuracy : 0.9967

In [118]:
torch.save(m3.state_dict(), "saved_models/m3.pth")

In [119]:
class MotorANN(nn.Module):
    
    def __init__(self):
        
        super().__init__()
        
        self.network = nn.Sequential(
            
            nn.Linear(4, 50),
            nn.Sigmoid(),
            
            nn.Linear(50, 50),
            nn.Sigmoid(),
            
            nn.Linear(50, 6)
        )
        
    def forward(self, x):
        
        return self.network(x)


m4 = MotorANN()

In [120]:
optimizer = torch.optim.Adam(m4.parameters(),lr=0.001)

In [121]:
train_step(m4 ,500 , acc , loss , optimizer , x2_train , y2_train , x2_test , y2_test)

  0%|          | 0/500 [00:00<?, ?it/s]

Epoch : 0  Train Loss : 0.6980  Test Loss : 0.6948  Accuracy : 0.5133
Epoch : 2  Train Loss : 0.6947  Test Loss : 0.6921  Accuracy : 0.5189
Epoch : 4  Train Loss : 0.6922  Test Loss : 0.6900  Accuracy : 0.5411
Epoch : 6  Train Loss : 0.6904  Test Loss : 0.6886  Accuracy : 0.5411
Epoch : 8  Train Loss : 0.6891  Test Loss : 0.6875  Accuracy : 0.5406
Epoch : 10  Train Loss : 0.6881  Test Loss : 0.6866  Accuracy : 0.5400
Epoch : 12  Train Loss : 0.6871  Test Loss : 0.6856  Accuracy : 0.5406
Epoch : 14  Train Loss : 0.6861  Test Loss : 0.6847  Accuracy : 0.5506
Epoch : 16  Train Loss : 0.6851  Test Loss : 0.6837  Accuracy : 0.6094
Epoch : 18  Train Loss : 0.6841  Test Loss : 0.6826  Accuracy : 0.6228
Epoch : 20  Train Loss : 0.6830  Test Loss : 0.6815  Accuracy : 0.6100
Epoch : 22  Train Loss : 0.6819  Test Loss : 0.6803  Accuracy : 0.6228
Epoch : 24  Train Loss : 0.6807  Test Loss : 0.6790  Accuracy : 0.6372
Epoch : 26  Train Loss : 0.6794  Test Loss : 0.6776  Accuracy : 0.6517
Epoch : 28  Train Loss : 0.6780  Test Loss : 0.6761  Accuracy : 0.6461
Epoch : 30  Train Loss : 0.6765  Test Loss : 0.6745  Accuracy : 0.6206
Epoch : 32  Train Loss : 0.6750  Test Loss : 0.6729  Accuracy : 0.5917
Epoch : 34  Train Loss : 0.6733  Test Loss : 0.6712  Accuracy : 0.5833
Epoch : 36  Train Loss : 0.6715  Test Loss : 0.6694  Accuracy : 0.5872
Epoch : 38  Train Loss : 0.6696  Test Loss : 0.6675  Accuracy : 0.5983
Epoch : 40  Train Loss : 0.6676  Test Loss : 0.6654  Accuracy : 0.6150
Epoch : 42  Train Loss : 0.6654  Test Loss : 0.6632  Accuracy : 0.6350
Epoch : 44  Train Loss : 0.6631  Test Loss : 0.6609  Accuracy : 0.6633
Epoch : 46  Train Loss : 0.6606  Test Loss : 0.6583  Accuracy : 0.6956
Epoch : 48  Train Loss : 0.6579  Test Loss : 0.6555  Accuracy : 0.7211
Epoch : 50  Train Loss : 0.6551  Test Loss : 0.6526  Accuracy : 0.7567
Epoch : 52  Train Loss : 0.6521  Test Loss : 0.6494  Accuracy : 0.7856
Epoch : 54  Train Loss : 0.6488  Test Loss : 0.6460  Accuracy : 0.8139
Epoch : 56  Train Loss : 0.6454  Test Loss : 0.6425  Accuracy : 0.8356
Epoch : 58  Train Loss : 0.6418  Test Loss : 0.6387  Accuracy : 0.8522
Epoch : 60  Train Loss : 0.6379  Test Loss : 0.6347  Accuracy : 0.8661
Epoch : 62  Train Loss : 0.6338  Test Loss : 0.6305  Accuracy : 0.8806
Epoch : 64  Train Loss : 0.6295  Test Loss : 0.6260  Accuracy : 0.8872
Epoch : 66  Train Loss : 0.6250  Test Loss : 0.6214  Accuracy : 0.8961
Epoch : 68  Train Loss : 0.6202  Test Loss : 0.6164  Accuracy : 0.9044
Epoch : 70  Train Loss : 0.6152  Test Loss : 0.6113  Accuracy : 0.9089
Epoch : 72  Train Loss : 0.6099  Test Loss : 0.6059  Accuracy : 0.9117
Epoch : 74  Train Loss : 0.6044  Test Loss : 0.6002  Accuracy : 0.9161
Epoch : 76  Train Loss : 0.5987  Test Loss : 0.5943  Accuracy : 0.9233
Epoch : 78  Train Loss : 0.5927  Test Loss : 0.5882  Accuracy : 0.9294
Epoch : 80  Train Loss : 0.5865  Test Loss : 0.5818  Accuracy : 0.9333
Epoch : 82  Train Loss : 0.5801  Test Loss : 0.5752  Accuracy : 0.9339
Epoch : 84  Train Loss : 0.5734  Test Loss : 0.5684  Accuracy : 0.9350
Epoch : 86  Train Loss : 0.5665  Test Loss : 0.5613  Accuracy : 0.9378
Epoch : 88  Train Loss : 0.5594  Test Loss : 0.5541  Accuracy : 0.9411
Epoch : 90  Train Loss : 0.5521  Test Loss : 0.5466  Accuracy : 0.9450
Epoch : 92  Train Loss : 0.5447  Test Loss : 0.5390  Accuracy : 0.9472
Epoch : 94  Train Loss : 0.5370  Test Loss : 0.5312  Accuracy : 0.9483
Epoch : 96  Train Loss : 0.5292  Test Loss : 0.5232  Accuracy : 0.9506
Epoch : 98  Train Loss : 0.5212  Test Loss : 0.5151  Accuracy : 0.9539
Epoch : 100  Train Loss : 0.5131  Test Loss : 0.5069  Accuracy : 0.9556
Epoch : 102  Train Loss : 0.5048  Test Loss : 0.4985  Accuracy : 0.9567
Epoch : 104  Train Loss : 0.4965  Test Loss : 0.4900  Accuracy : 0.9583
Epoch : 106  Train Loss : 0.4880  Test Loss : 0.4815  Accuracy : 0.9583
Epoch : 108  Train Loss : 0.4795  Test Loss : 0.4729  Accuracy : 0.9583
Epoch : 110  Train Loss : 0.4709  Test Loss : 0.4642  Accuracy : 0.9589
Epoch : 112  Train Loss : 0.4623  Test Loss : 0.4555  Accuracy : 0.9594
Epoch : 114  Train Loss : 0.4537  Test Loss : 0.4468  Accuracy : 0.9611
Epoch : 116  Train Loss : 0.4451  Test Loss : 0.4382  Accuracy : 0.9622
Epoch : 118  Train Loss : 0.4365  Test Loss : 0.4295  Accuracy : 0.9628
Epoch : 120  Train Loss : 0.4279  Test Loss : 0.4209  Accuracy : 0.9650
Epoch : 122  Train Loss : 0.4193  Test Loss : 0.4124  Accuracy : 0.9661
Epoch : 124  Train Loss : 0.4109  Test Loss : 0.4039  Accuracy : 0.9667
Epoch : 126  Train Loss : 0.4025  Test Loss : 0.3955  Accuracy : 0.9683
Epoch : 128  Train Loss : 0.3942  Test Loss : 0.3873  Accuracy : 0.9689
Epoch : 130  Train Loss : 0.3860  Test Loss : 0.3791  Accuracy : 0.9706
Epoch : 132  Train Loss : 0.3779  Test Loss : 0.3711  Accuracy : 0.9717
Epoch : 134  Train Loss : 0.3700  Test Loss : 0.3632  Accuracy : 0.9722
Epoch : 136  Train Loss : 0.3622  Test Loss : 0.3555  Accuracy : 0.9728
Epoch : 138  Train Loss : 0.3545  Test Loss : 0.3480  Accuracy : 0.9739
Epoch : 140  Train Loss : 0.3470  Test Loss : 0.3406  Accuracy : 0.9750
Epoch : 142  Train Loss : 0.3397  Test Loss : 0.3334  Accuracy : 0.9750
Epoch : 144  Train Loss : 0.3325  Test Loss : 0.3263  Accuracy : 0.9761
Epoch : 146  Train Loss : 0.3255  Test Loss : 0.3195  Accuracy : 0.9767
Epoch : 148  Train Loss : 0.3187  Test Loss : 0.3128  Accuracy : 0.9767
Epoch : 150  Train Loss : 0.3121  Test Loss : 0.3063  Accuracy : 0.9778
Epoch : 152  Train Loss : 0.3057  Test Loss : 0.3000  Accuracy : 0.9778
Epoch : 154  Train Loss : 0.2994  Test Loss : 0.2939  Accuracy : 0.9783
Epoch : 156  Train Loss : 0.2933  Test Loss : 0.2880  Accuracy : 0.9794
Epoch : 158  Train Loss : 0.2874  Test Loss : 0.2823  Accuracy : 0.9806
Epoch : 160  Train Loss : 0.2817  Test Loss : 0.2767  Accuracy : 0.9817
Epoch : 162  Train Loss : 0.2762  Test Loss : 0.2714  Accuracy : 0.9822
Epoch : 164  Train Loss : 0.2708  Test Loss : 0.2662  Accuracy : 0.9828
Epoch : 166  Train Loss : 0.2657  Test Loss : 0.2612  Accuracy : 0.9833
Epoch : 168  Train Loss : 0.2607  Test Loss : 0.2563  Accuracy : 0.9844
Epoch : 170  Train Loss : 0.2558  Test Loss : 0.2516  Accuracy : 0.9839
Epoch : 172  Train Loss : 0.2512  Test Loss : 0.2471  Accuracy : 0.9844
Epoch : 174  Train Loss : 0.2466  Test Loss : 0.2427  Accuracy : 0.9856
Epoch : 176  Train Loss : 0.2423  Test Loss : 0.2385  Accuracy : 0.9856
Epoch : 178  Train Loss : 0.2381  Test Loss : 0.2345  Accuracy : 0.9861
Epoch : 180  Train Loss : 0.2340  Test Loss : 0.2305  Accuracy : 0.9867
Epoch : 182  Train Loss : 0.2301  Test Loss : 0.2268  Accuracy : 0.9867
Epoch : 184  Train Loss : 0.2263  Test Loss : 0.2231  Accuracy : 0.9867
Epoch : 186  Train Loss : 0.2226  Test Loss : 0.2196  Accuracy : 0.9878
Epoch : 188  Train Loss : 0.2191  Test Loss : 0.2162  Accuracy : 0.9883
Epoch : 190  Train Loss : 0.2157  Test Loss : 0.2129  Accuracy : 0.9894
Epoch : 192  Train Loss : 0.2124  Test Loss : 0.2097  Accuracy : 0.9894
Epoch : 194  Train Loss : 0.2092  Test Loss : 0.2067  Accuracy : 0.9894
Epoch : 196  Train Loss : 0.2062  Test Loss : 0.2037  Accuracy : 0.9900
Epoch : 198  Train Loss : 0.2032  Test Loss : 0.2008  Accuracy : 0.9900
Epoch : 200  Train Loss : 0.2003  Test Loss : 0.1981  Accuracy : 0.9906
Epoch : 202  Train Loss : 0.1976  Test Loss : 0.1954  Accuracy : 0.9911
Epoch : 204  Train Loss : 0.1949  Test Loss : 0.1928  Accuracy : 0.9917
Epoch : 206  Train Loss : 0.1923  Test Loss : 0.1903  Accuracy : 0.9922
Epoch : 208  Train Loss : 0.1898  Test Loss : 0.1879  Accuracy : 0.9922
Epoch : 210  Train Loss : 0.1874  Test Loss : 0.1856  Accuracy : 0.9917
Epoch : 212  Train Loss : 0.1850  Test Loss : 0.1833  Accuracy : 0.9917
Epoch : 214  Train Loss : 0.1828  Test Loss : 0.1811  Accuracy : 0.9917
Epoch : 216  Train Loss : 0.1806  Test Loss : 0.1790  Accuracy : 0.9917
Epoch : 218  Train Loss : 0.1784  Test Loss : 0.1770  Accuracy : 0.9917
Epoch : 220  Train Loss : 0.1764  Test Loss : 0.1750  Accuracy : 0.9917
Epoch : 222  Train Loss : 0.1744  Test Loss : 0.1730  Accuracy : 0.9917
Epoch : 224  Train Loss : 0.1724  Test Loss : 0.1712  Accuracy : 0.9922
Epoch : 226  Train Loss : 0.1705  Test Loss : 0.1693  Accuracy : 0.9939
Epoch : 228  Train Loss : 0.1687  Test Loss : 0.1676  Accuracy : 0.9944
Epoch : 230  Train Loss : 0.1669  Test Loss : 0.1659  Accuracy : 0.9944
Epoch : 232  Train Loss : 0.1652  Test Loss : 0.1642  Accuracy : 0.9944
Epoch : 234  Train Loss : 0.1635  Test Loss : 0.1626  Accuracy : 0.9944
Epoch : 236  Train Loss : 0.1619  Test Loss : 0.1610  Accuracy : 0.9944
Epoch : 238  Train Loss : 0.1603  Test Loss : 0.1595  Accuracy : 0.9944
Epoch : 240  Train Loss : 0.1588  Test Loss : 0.1580  Accuracy : 0.9944
Epoch : 242  Train Loss : 0.1573  Test Loss : 0.1565  Accuracy : 0.9950
Epoch : 244  Train Loss : 0.1558  Test Loss : 0.1551  Accuracy : 0.9956
Epoch : 246  Train Loss : 0.1544  Test Loss : 0.1537  Accuracy : 0.9956
Epoch : 248  Train Loss : 0.1530  Test Loss : 0.1524  Accuracy : 0.9956
Epoch : 250  Train Loss : 0.1516  Test Loss : 0.1511  Accuracy : 0.9956
Epoch : 252  Train Loss : 0.1503  Test Loss : 0.1498  Accuracy : 0.9961
Epoch : 254  Train Loss : 0.1490  Test Loss : 0.1486  Accuracy : 0.9961
Epoch : 256  Train Loss : 0.1478  Test Loss : 0.1473  Accuracy : 0.9961
Epoch : 258  Train Loss : 0.1465  Test Loss : 0.1462  Accuracy : 0.9961
Epoch : 260  Train Loss : 0.1453  Test Loss : 0.1450  Accuracy : 0.9961
Epoch : 262  Train Loss : 0.1442  Test Loss : 0.1439  Accuracy : 0.9961
Epoch : 264  Train Loss : 0.1430  Test Loss : 0.1428  Accuracy : 0.9961
Epoch : 266  Train Loss : 0.1419  Test Loss : 0.1417  Accuracy : 0.9961
Epoch : 268  Train Loss : 0.1408  Test Loss : 0.1406  Accuracy : 0.9967
Epoch : 270  Train Loss : 0.1398  Test Loss : 0.1396  Accuracy : 0.9967
Epoch : 272  Train Loss : 0.1387  Test Loss : 0.1386  Accuracy : 0.9967
Epoch : 274  Train Loss : 0.1377  Test Loss : 0.1376  Accuracy : 0.9967
Epoch : 276  Train Loss : 0.1367  Test Loss : 0.1366  Accuracy : 0.9967
Epoch : 278  Train Loss : 0.1357  Test Loss : 0.1357  Accuracy : 0.9967
Epoch : 280  Train Loss : 0.1348  Test Loss : 0.1348  Accuracy : 0.9967
Epoch : 282  Train Loss : 0.1338  Test Loss : 0.1338  Accuracy : 0.9967
Epoch : 284  Train Loss : 0.1329  Test Loss : 0.1330  Accuracy : 0.9967
Epoch : 286  Train Loss : 0.1320  Test Loss : 0.1321  Accuracy : 0.9967
Epoch : 288  Train Loss : 0.1311  Test Loss : 0.1312  Accuracy : 0.9967
Epoch : 290  Train Loss : 0.1303  Test Loss : 0.1304  Accuracy : 0.9967
Epoch : 292  Train Loss : 0.1294  Test Loss : 0.1296  Accuracy : 0.9967
Epoch : 294  Train Loss : 0.1286  Test Loss : 0.1288  Accuracy : 0.9967
Epoch : 296  Train Loss : 0.1278  Test Loss : 0.1280  Accuracy : 0.9967
Epoch : 298  Train Loss : 0.1270  Test Loss : 0.1272  Accuracy : 0.9967
Epoch : 300  Train Loss : 0.1262  Test Loss : 0.1264  Accuracy : 0.9967
Epoch : 302  Train Loss : 0.1254  Test Loss : 0.1257  Accuracy : 0.9967
Epoch : 304  Train Loss : 0.1246  Test Loss : 0.1249  Accuracy : 0.9967
Epoch : 306  Train Loss : 0.1239  Test Loss : 0.1242  Accuracy : 0.9967
Epoch : 308  Train Loss : 0.1232  Test Loss : 0.1235  Accuracy : 0.9967
Epoch : 310  Train Loss : 0.1224  Test Loss : 0.1228  Accuracy : 0.9967
Epoch : 312  Train Loss : 0.1217  Test Loss : 0.1221  Accuracy : 0.9967
Epoch : 314  Train Loss : 0.1210  Test Loss : 0.1214  Accuracy : 0.9967
Epoch : 316  Train Loss : 0.1204  Test Loss : 0.1207  Accuracy : 0.9967
Epoch : 318  Train Loss : 0.1197  Test Loss : 0.1201  Accuracy : 0.9967
Epoch : 320  Train Loss : 0.1190  Test Loss : 0.1194  Accuracy : 0.9967
Epoch : 322  Train Loss : 0.1184  Test Loss : 0.1188  Accuracy : 0.9967
Epoch : 324  Train Loss : 0.1177  Test Loss : 0.1182  Accuracy : 0.9967
Epoch : 326  Train Loss : 0.1171  Test Loss : 0.1176  Accuracy : 0.9967
Epoch : 328  Train Loss : 0.1165  Test Loss : 0.1170  Accuracy : 0.9967
Epoch : 330  Train Loss : 0.1159  Test Loss : 0.1164  Accuracy : 0.9967
Epoch : 332  Train Loss : 0.1153  Test Loss : 0.1158  Accuracy : 0.9967
Epoch : 334  Train Loss : 0.1147  Test Loss : 0.1152  Accuracy : 0.9967
Epoch : 336  Train Loss : 0.1141  Test Loss : 0.1146  Accuracy : 0.9967
Epoch : 338  Train Loss : 0.1135  Test Loss : 0.1140  Accuracy : 0.9967
Epoch : 340  Train Loss : 0.1129  Test Loss : 0.1135  Accuracy : 0.9967
Epoch : 342  Train Loss : 0.1124  Test Loss : 0.1129  Accuracy : 0.9967
Epoch : 344  Train Loss : 0.1118  Test Loss : 0.1124  Accuracy : 0.9967
Epoch : 346  Train Loss : 0.1113  Test Loss : 0.1119  Accuracy : 0.9967
Epoch : 348  Train Loss : 0.1107  Test Loss : 0.1113  Accuracy : 0.9967
Epoch : 350  Train Loss : 0.1102  Test Loss : 0.1108  Accuracy : 0.9967
Epoch : 352  Train Loss : 0.1097  Test Loss : 0.1103  Accuracy : 0.9967
Epoch : 354  Train Loss : 0.1091  Test Loss : 0.1098  Accuracy : 0.9967
Epoch : 356  Train Loss : 0.1086  Test Loss : 0.1093  Accuracy : 0.9967
Epoch : 358  Train Loss : 0.1081  Test Loss : 0.1088  Accuracy : 0.9967
Epoch : 360  Train Loss : 0.1076  Test Loss : 0.1083  Accuracy : 0.9967
Epoch : 362  Train Loss : 0.1071  Test Loss : 0.1078  Accuracy : 0.9967
Epoch : 364  Train Loss : 0.1067  Test Loss : 0.1074  Accuracy : 0.9967
Epoch : 366  Train Loss : 0.1062  Test Loss : 0.1069  Accuracy : 0.9967
Epoch : 368  Train Loss : 0.1057  Test Loss : 0.1064  Accuracy : 0.9967
Epoch : 370  Train Loss : 0.1052  Test Loss : 0.1060  Accuracy : 0.9967
Epoch : 372  Train Loss : 0.1048  Test Loss : 0.1055  Accuracy : 0.9967
Epoch : 374  Train Loss : 0.1043  Test Loss : 0.1051  Accuracy : 0.9967
Epoch : 376  Train Loss : 0.1039  Test Loss : 0.1046  Accuracy : 0.9967
Epoch : 378  Train Loss : 0.1034  Test Loss : 0.1042  Accuracy : 0.9967
Epoch : 380  Train Loss : 0.1030  Test Loss : 0.1037  Accuracy : 0.9967
Epoch : 382  Train Loss : 0.1025  Test Loss : 0.1033  Accuracy : 0.9967
Epoch : 384  Train Loss : 0.1021  Test Loss : 0.1029  Accuracy : 0.9967
Epoch : 386  Train Loss : 0.1017  Test Loss : 0.1025  Accuracy : 0.9967
Epoch : 388  Train Loss : 0.1013  Test Loss : 0.1020  Accuracy : 0.9967
Epoch : 390  Train Loss : 0.1008  Test Loss : 0.1016  Accuracy : 0.9967
Epoch : 392  Train Loss : 0.1004  Test Loss : 0.1012  Accuracy : 0.9967
Epoch : 394  Train Loss : 0.1000  Test Loss : 0.1008  Accuracy : 0.9967
Epoch : 396  Train Loss : 0.0996  Test Loss : 0.1004  Accuracy : 0.9967
Epoch : 398  Train Loss : 0.0992  Test Loss : 0.1000  Accuracy : 0.9967
Epoch : 400  Train Loss : 0.0988  Test Loss : 0.0996  Accuracy : 0.9967
Epoch : 402  Train Loss : 0.0984  Test Loss : 0.0992  Accuracy : 0.9967
Epoch : 404  Train Loss : 0.0980  Test Loss : 0.0989  Accuracy : 0.9967
Epoch : 406  Train Loss : 0.0976  Test Loss : 0.0985  Accuracy : 0.9967
Epoch : 408  Train Loss : 0.0973  Test Loss : 0.0981  Accuracy : 0.9967
Epoch : 410  Train Loss : 0.0969  Test Loss : 0.0977  Accuracy : 0.9967
Epoch : 412  Train Loss : 0.0965  Test Loss : 0.0974  Accuracy : 0.9967
Epoch : 414  Train Loss : 0.0961  Test Loss : 0.0970  Accuracy : 0.9967
Epoch : 416  Train Loss : 0.0958  Test Loss : 0.0966  Accuracy : 0.9967
Epoch : 418  Train Loss : 0.0954  Test Loss : 0.0963  Accuracy : 0.9967
Epoch : 420  Train Loss : 0.0950  Test Loss : 0.0959  Accuracy : 0.9967
Epoch : 422  Train Loss : 0.0947  Test Loss : 0.0956  Accuracy : 0.9967
Epoch : 424  Train Loss : 0.0943  Test Loss : 0.0952  Accuracy : 0.9967
Epoch : 426  Train Loss : 0.0940  Test Loss : 0.0949  Accuracy : 0.9967
Epoch : 428  Train Loss : 0.0936  Test Loss : 0.0945  Accuracy : 0.9967
Epoch : 430  Train Loss : 0.0933  Test Loss : 0.0942  Accuracy : 0.9967
Epoch : 432  Train Loss : 0.0929  Test Loss : 0.0938  Accuracy : 0.9967
Epoch : 434  Train Loss : 0.0926  Test Loss : 0.0935  Accuracy : 0.9967
Epoch : 436  Train Loss : 0.0923  Test Loss : 0.0932  Accuracy : 0.9967
Epoch : 438  Train Loss : 0.0919  Test Loss : 0.0928  Accuracy : 0.9967
Epoch : 440  Train Loss : 0.0916  Test Loss : 0.0925  Accuracy : 0.9967
Epoch : 442  Train Loss : 0.0913  Test Loss : 0.0922  Accuracy : 0.9967
Epoch : 444  Train Loss : 0.0910  Test Loss : 0.0919  Accuracy : 0.9967
Epoch : 446  Train Loss : 0.0906  Test Loss : 0.0915  Accuracy : 0.9967
Epoch : 448  Train Loss : 0.0903  Test Loss : 0.0912  Accuracy : 0.9967
Epoch : 450  Train Loss : 0.0900  Test Loss : 0.0909  Accuracy : 0.9967
Epoch : 452  Train Loss : 0.0897  Test Loss : 0.0906  Accuracy : 0.9967
Epoch : 454  Train Loss : 0.0894  Test Loss : 0.0903  Accuracy : 0.9967
Epoch : 456  Train Loss : 0.0891  Test Loss : 0.0900  Accuracy : 0.9967
Epoch : 458  Train Loss : 0.0887  Test Loss : 0.0897  Accuracy : 0.9967
Epoch : 460  Train Loss : 0.0884  Test Loss : 0.0894  Accuracy : 0.9967
Epoch : 462  Train Loss : 0.0881  Test Loss : 0.0890  Accuracy : 0.9967
Epoch : 464  Train Loss : 0.0878  Test Loss : 0.0887  Accuracy : 0.9967
Epoch : 466  Train Loss : 0.0875  Test Loss : 0.0884  Accuracy : 0.9967
Epoch : 468  Train Loss : 0.0872  Test Loss : 0.0882  Accuracy : 0.9967
Epoch : 470  Train Loss : 0.0869  Test Loss : 0.0879  Accuracy : 0.9967
Epoch : 472  Train Loss : 0.0867  Test Loss : 0.0876  Accuracy : 0.9967
Epoch : 474  Train Loss : 0.0864  Test Loss : 0.0873  Accuracy : 0.9967
Epoch : 476  Train Loss : 0.0861  Test Loss : 0.0870  Accuracy : 0.9967
Epoch : 478  Train Loss : 0.0858  Test Loss : 0.0867  Accuracy : 0.9967
Epoch : 480  Train Loss : 0.0855  Test Loss : 0.0864  Accuracy : 0.9967
Epoch : 482  Train Loss : 0.0852  Test Loss : 0.0861  Accuracy : 0.9967
Epoch : 484  Train Loss : 0.0849  Test Loss : 0.0859  Accuracy : 0.9967
Epoch : 486  Train Loss : 0.0847  Test Loss : 0.0856  Accuracy : 0.9967
Epoch : 488  Train Loss : 0.0844  Test Loss : 0.0853  Accuracy : 0.9967
Epoch : 490  Train Loss : 0.0841  Test Loss : 0.0850  Accuracy : 0.9967
Epoch : 492  Train Loss : 0.0838  Test Loss : 0.0847  Accuracy : 0.9967
Epoch : 494  Train Loss : 0.0836  Test Loss : 0.0845  Accuracy : 0.9967
Epoch : 496  Train Loss : 0.0833  Test Loss : 0.0842  Accuracy : 0.9967
Epoch : 498  Train Loss : 0.0830  Test Loss : 0.0839  Accuracy : 0.9967

In [122]:
torch.save(m4.state_dict(), "saved_models/m4.pth")

In [123]:

class ModernANN(nn.Module):
    
    def __init__(self):
        
        super().__init__()
        
        self.network = nn.Sequential(
            
            nn.Linear(4, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            
            nn.Linear(64, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            
            nn.Linear(64, 6)
        )
        
    def forward(self, x):
        
        return self.network(x)


m5 = ModernANN()

In [124]:
modern_optimizer = torch.optim.Adam(
    m5.parameters(),
    lr=0.001,
    weight_decay=1e-4
)

In [125]:
train_step(m5 ,500 , acc , loss , modern_optimizer , x2_train , y2_train , x2_test , y2_test)

  0%|          | 0/500 [00:00<?, ?it/s]

Epoch : 0  Train Loss : 0.6871  Test Loss : 0.6820  Accuracy : 0.5978
Epoch : 2  Train Loss : 0.6775  Test Loss : 0.6730  Accuracy : 0.6689
Epoch : 4  Train Loss : 0.6686  Test Loss : 0.6638  Accuracy : 0.7200
Epoch : 6  Train Loss : 0.6595  Test Loss : 0.6545  Accuracy : 0.7572
Epoch : 8  Train Loss : 0.6509  Test Loss : 0.6449  Accuracy : 0.7772
Epoch : 10  Train Loss : 0.6400  Test Loss : 0.6348  Accuracy : 0.8056
Epoch : 12  Train Loss : 0.6311  Test Loss : 0.6241  Accuracy : 0.8294
Epoch : 14  Train Loss : 0.6205  Test Loss : 0.6128  Accuracy : 0.8589
Epoch : 16  Train Loss : 0.6077  Test Loss : 0.6007  Accuracy : 0.8717
Epoch : 18  Train Loss : 0.5953  Test Loss : 0.5877  Accuracy : 0.8789
Epoch : 20  Train Loss : 0.5830  Test Loss : 0.5739  Accuracy : 0.8878
Epoch : 22  Train Loss : 0.5676  Test Loss : 0.5592  Accuracy : 0.8939
Epoch : 24  Train Loss : 0.5544  Test Loss : 0.5437  Accuracy : 0.9017
Epoch : 26  Train Loss : 0.5388  Test Loss : 0.5273  Accuracy : 0.9067
Epoch : 28  Train Loss : 0.5230  Test Loss : 0.5102  Accuracy : 0.9111
Epoch : 30  Train Loss : 0.5072  Test Loss : 0.4925  Accuracy : 0.9172
Epoch : 32  Train Loss : 0.4910  Test Loss : 0.4742  Accuracy : 0.9211
Epoch : 34  Train Loss : 0.4709  Test Loss : 0.4557  Accuracy : 0.9228
Epoch : 36  Train Loss : 0.4540  Test Loss : 0.4368  Accuracy : 0.9278
Epoch : 38  Train Loss : 0.4372  Test Loss : 0.4179  Accuracy : 0.9317
Epoch : 40  Train Loss : 0.4142  Test Loss : 0.3990  Accuracy : 0.9350
Epoch : 42  Train Loss : 0.3980  Test Loss : 0.3803  Accuracy : 0.9383
Epoch : 44  Train Loss : 0.3774  Test Loss : 0.3618  Accuracy : 0.9406
Epoch : 46  Train Loss : 0.3640  Test Loss : 0.3438  Accuracy : 0.9417
Epoch : 48  Train Loss : 0.3407  Test Loss : 0.3262  Accuracy : 0.9439
Epoch : 50  Train Loss : 0.3262  Test Loss : 0.3092  Accuracy : 0.9483
Epoch : 52  Train Loss : 0.3121  Test Loss : 0.2929  Accuracy : 0.9522
Epoch : 54  Train Loss : 0.2924  Test Loss : 0.2774  Accuracy : 0.9550
Epoch : 56  Train Loss : 0.2831  Test Loss : 0.2626  Accuracy : 0.9583
Epoch : 58  Train Loss : 0.2671  Test Loss : 0.2487  Accuracy : 0.9622
Epoch : 60  Train Loss : 0.2527  Test Loss : 0.2355  Accuracy : 0.9661
Epoch : 62  Train Loss : 0.2406  Test Loss : 0.2232  Accuracy : 0.9694
Epoch : 64  Train Loss : 0.2281  Test Loss : 0.2116  Accuracy : 0.9711
Epoch : 66  Train Loss : 0.2243  Test Loss : 0.2009  Accuracy : 0.9744
Epoch : 68  Train Loss : 0.2142  Test Loss : 0.1910  Accuracy : 0.9761
Epoch : 70  Train Loss : 0.2010  Test Loss : 0.1819  Accuracy : 0.9767
Epoch : 72  Train Loss : 0.1938  Test Loss : 0.1736  Accuracy : 0.9794
Epoch : 74  Train Loss : 0.1824  Test Loss : 0.1659  Accuracy : 0.9822
Epoch : 76  Train Loss : 0.1801  Test Loss : 0.1589  Accuracy : 0.9833
Epoch : 78  Train Loss : 0.1712  Test Loss : 0.1525  Accuracy : 0.9833
Epoch : 80  Train Loss : 0.1635  Test Loss : 0.1466  Accuracy : 0.9844
Epoch : 82  Train Loss : 0.1625  Test Loss : 0.1411  Accuracy : 0.9856
Epoch : 84  Train Loss : 0.1549  Test Loss : 0.1360  Accuracy : 0.9861
Epoch : 86  Train Loss : 0.1504  Test Loss : 0.1312  Accuracy : 0.9861
Epoch : 88  Train Loss : 0.1468  Test Loss : 0.1268  Accuracy : 0.9872
Epoch : 90  Train Loss : 0.1416  Test Loss : 0.1227  Accuracy : 0.9872
Epoch : 92  Train Loss : 0.1424  Test Loss : 0.1188  Accuracy : 0.9889
Epoch : 94  Train Loss : 0.1419  Test Loss : 0.1152  Accuracy : 0.9906
Epoch : 96  Train Loss : 0.1319  Test Loss : 0.1119  Accuracy : 0.9917
Epoch : 98  Train Loss : 0.1303  Test Loss : 0.1088  Accuracy : 0.9917
Epoch : 100  Train Loss : 0.1222  Test Loss : 0.1060  Accuracy : 0.9911
Epoch : 102  Train Loss : 0.1225  Test Loss : 0.1035  Accuracy : 0.9922
Epoch : 104  Train Loss : 0.1226  Test Loss : 0.1012  Accuracy : 0.9917
Epoch : 106  Train Loss : 0.1220  Test Loss : 0.0989  Accuracy : 0.9917
Epoch : 108  Train Loss : 0.1250  Test Loss : 0.0968  Accuracy : 0.9917
Epoch : 110  Train Loss : 0.1151  Test Loss : 0.0947  Accuracy : 0.9917
Epoch : 112  Train Loss : 0.1117  Test Loss : 0.0928  Accuracy : 0.9917
Epoch : 114  Train Loss : 0.1140  Test Loss : 0.0909  Accuracy : 0.9917
Epoch : 116  Train Loss : 0.1128  Test Loss : 0.0890  Accuracy : 0.9906
Epoch : 118  Train Loss : 0.1133  Test Loss : 0.0875  Accuracy : 0.9911
Epoch : 120  Train Loss : 0.1086  Test Loss : 0.0861  Accuracy : 0.9917
Epoch : 122  Train Loss : 0.1051  Test Loss : 0.0847  Accuracy : 0.9911
Epoch : 124  Train Loss : 0.1034  Test Loss : 0.0834  Accuracy : 0.9911
Epoch : 126  Train Loss : 0.0998  Test Loss : 0.0821  Accuracy : 0.9917
Epoch : 128  Train Loss : 0.0982  Test Loss : 0.0808  Accuracy : 0.9917
Epoch : 130  Train Loss : 0.0987  Test Loss : 0.0795  Accuracy : 0.9917
Epoch : 132  Train Loss : 0.1099  Test Loss : 0.0781  Accuracy : 0.9917
Epoch : 134  Train Loss : 0.0960  Test Loss : 0.0767  Accuracy : 0.9922
Epoch : 136  Train Loss : 0.0945  Test Loss : 0.0753  Accuracy : 0.9922
Epoch : 138  Train Loss : 0.0940  Test Loss : 0.0740  Accuracy : 0.9939
Epoch : 140  Train Loss : 0.0983  Test Loss : 0.0727  Accuracy : 0.9944
Epoch : 142  Train Loss : 0.0973  Test Loss : 0.0716  Accuracy : 0.9944
Epoch : 144  Train Loss : 0.0949  Test Loss : 0.0705  Accuracy : 0.9944
Epoch : 146  Train Loss : 0.0916  Test Loss : 0.0697  Accuracy : 0.9950
Epoch : 148  Train Loss : 0.0933  Test Loss : 0.0689  Accuracy : 0.9944
Epoch : 150  Train Loss : 0.0966  Test Loss : 0.0682  Accuracy : 0.9928
Epoch : 152  Train Loss : 0.0880  Test Loss : 0.0675  Accuracy : 0.9928
Epoch : 154  Train Loss : 0.0922  Test Loss : 0.0670  Accuracy : 0.9917
Epoch : 156  Train Loss : 0.0880  Test Loss : 0.0665  Accuracy : 0.9917
Epoch : 158  Train Loss : 0.0907  Test Loss : 0.0658  Accuracy : 0.9917
Epoch : 160  Train Loss : 0.0865  Test Loss : 0.0651  Accuracy : 0.9917
Epoch : 162  Train Loss : 0.0855  Test Loss : 0.0644  Accuracy : 0.9911
Epoch : 164  Train Loss : 0.0857  Test Loss : 0.0637  Accuracy : 0.9911
Epoch : 166  Train Loss : 0.0869  Test Loss : 0.0630  Accuracy : 0.9911
Epoch : 168  Train Loss : 0.0865  Test Loss : 0.0621  Accuracy : 0.9922
Epoch : 170  Train Loss : 0.0872  Test Loss : 0.0613  Accuracy : 0.9922
Epoch : 172  Train Loss : 0.0816  Test Loss : 0.0605  Accuracy : 0.9939
Epoch : 174  Train Loss : 0.0837  Test Loss : 0.0598  Accuracy : 0.9950
Epoch : 176  Train Loss : 0.0831  Test Loss : 0.0592  Accuracy : 0.9950
Epoch : 178  Train Loss : 0.0832  Test Loss : 0.0586  Accuracy : 0.9950
Epoch : 180  Train Loss : 0.0839  Test Loss : 0.0581  Accuracy : 0.9950
Epoch : 182  Train Loss : 0.0812  Test Loss : 0.0577  Accuracy : 0.9956
Epoch : 184  Train Loss : 0.0785  Test Loss : 0.0573  Accuracy : 0.9950
Epoch : 186  Train Loss : 0.0841  Test Loss : 0.0569  Accuracy : 0.9956
Epoch : 188  Train Loss : 0.0847  Test Loss : 0.0563  Accuracy : 0.9956
Epoch : 190  Train Loss : 0.0833  Test Loss : 0.0556  Accuracy : 0.9956
Epoch : 192  Train Loss : 0.0784  Test Loss : 0.0549  Accuracy : 0.9956
Epoch : 194  Train Loss : 0.0799  Test Loss : 0.0543  Accuracy : 0.9967
Epoch : 196  Train Loss : 0.0741  Test Loss : 0.0538  Accuracy : 0.9950
Epoch : 198  Train Loss : 0.0770  Test Loss : 0.0532  Accuracy : 0.9944
Epoch : 200  Train Loss : 0.0729  Test Loss : 0.0527  Accuracy : 0.9950
Epoch : 202  Train Loss : 0.0757  Test Loss : 0.0523  Accuracy : 0.9950
Epoch : 204  Train Loss : 0.0726  Test Loss : 0.0520  Accuracy : 0.9944
Epoch : 206  Train Loss : 0.0785  Test Loss : 0.0518  Accuracy : 0.9939
Epoch : 208  Train Loss : 0.0742  Test Loss : 0.0515  Accuracy : 0.9944
Epoch : 210  Train Loss : 0.0777  Test Loss : 0.0513  Accuracy : 0.9944
Epoch : 212  Train Loss : 0.0708  Test Loss : 0.0508  Accuracy : 0.9944
Epoch : 214  Train Loss : 0.0709  Test Loss : 0.0503  Accuracy : 0.9950
Epoch : 216  Train Loss : 0.0764  Test Loss : 0.0497  Accuracy : 0.9961
Epoch : 218  Train Loss : 0.0716  Test Loss : 0.0493  Accuracy : 0.9961
Epoch : 220  Train Loss : 0.0697  Test Loss : 0.0488  Accuracy : 0.9961
Epoch : 222  Train Loss : 0.0720  Test Loss : 0.0485  Accuracy : 0.9956
Epoch : 224  Train Loss : 0.0713  Test Loss : 0.0482  Accuracy : 0.9950
Epoch : 226  Train Loss : 0.0670  Test Loss : 0.0479  Accuracy : 0.9956
Epoch : 228  Train Loss : 0.0725  Test Loss : 0.0477  Accuracy : 0.9950
Epoch : 230  Train Loss : 0.0678  Test Loss : 0.0476  Accuracy : 0.9950
Epoch : 232  Train Loss : 0.0639  Test Loss : 0.0475  Accuracy : 0.9950
Epoch : 234  Train Loss : 0.0731  Test Loss : 0.0474  Accuracy : 0.9956
Epoch : 236  Train Loss : 0.0705  Test Loss : 0.0474  Accuracy : 0.9939
Epoch : 238  Train Loss : 0.0684  Test Loss : 0.0473  Accuracy : 0.9933
Epoch : 240  Train Loss : 0.0626  Test Loss : 0.0470  Accuracy : 0.9939
Epoch : 242  Train Loss : 0.0679  Test Loss : 0.0467  Accuracy : 0.9944
Epoch : 244  Train Loss : 0.0685  Test Loss : 0.0463  Accuracy : 0.9944
Epoch : 246  Train Loss : 0.0675  Test Loss : 0.0457  Accuracy : 0.9961
Epoch : 248  Train Loss : 0.0645  Test Loss : 0.0451  Accuracy : 0.9967
Epoch : 250  Train Loss : 0.0637  Test Loss : 0.0446  Accuracy : 0.9967
Epoch : 252  Train Loss : 0.0671  Test Loss : 0.0443  Accuracy : 0.9967
Epoch : 254  Train Loss : 0.0670  Test Loss : 0.0440  Accuracy : 0.9967
Epoch : 256  Train Loss : 0.0641  Test Loss : 0.0438  Accuracy : 0.9967
Epoch : 258  Train Loss : 0.0657  Test Loss : 0.0436  Accuracy : 0.9950
Epoch : 260  Train Loss : 0.0671  Test Loss : 0.0434  Accuracy : 0.9944
Epoch : 262  Train Loss : 0.0593  Test Loss : 0.0433  Accuracy : 0.9944
Epoch : 264  Train Loss : 0.0605  Test Loss : 0.0429  Accuracy : 0.9944
Epoch : 266  Train Loss : 0.0663  Test Loss : 0.0428  Accuracy : 0.9944
Epoch : 268  Train Loss : 0.0622  Test Loss : 0.0428  Accuracy : 0.9944
Epoch : 270  Train Loss : 0.0639  Test Loss : 0.0428  Accuracy : 0.9944
Epoch : 272  Train Loss : 0.0659  Test Loss : 0.0427  Accuracy : 0.9950
Epoch : 274  Train Loss : 0.0617  Test Loss : 0.0424  Accuracy : 0.9933
Epoch : 276  Train Loss : 0.0631  Test Loss : 0.0420  Accuracy : 0.9933
Epoch : 278  Train Loss : 0.0644  Test Loss : 0.0415  Accuracy : 0.9944
Epoch : 280  Train Loss : 0.0620  Test Loss : 0.0410  Accuracy : 0.9961
Epoch : 282  Train Loss : 0.0608  Test Loss : 0.0406  Accuracy : 0.9967
Epoch : 284  Train Loss : 0.0698  Test Loss : 0.0402  Accuracy : 0.9967
Epoch : 286  Train Loss : 0.0561  Test Loss : 0.0398  Accuracy : 0.9967
Epoch : 288  Train Loss : 0.0669  Test Loss : 0.0394  Accuracy : 0.9967
Epoch : 290  Train Loss : 0.0607  Test Loss : 0.0391  Accuracy : 0.9967
Epoch : 292  Train Loss : 0.0617  Test Loss : 0.0389  Accuracy : 0.9967
Epoch : 294  Train Loss : 0.0593  Test Loss : 0.0389  Accuracy : 0.9967
Epoch : 296  Train Loss : 0.0569  Test Loss : 0.0388  Accuracy : 0.9967
Epoch : 298  Train Loss : 0.0626  Test Loss : 0.0390  Accuracy : 0.9956
Epoch : 300  Train Loss : 0.0605  Test Loss : 0.0391  Accuracy : 0.9956
Epoch : 302  Train Loss : 0.0586  Test Loss : 0.0392  Accuracy : 0.9939
Epoch : 304  Train Loss : 0.0648  Test Loss : 0.0390  Accuracy : 0.9939
Epoch : 306  Train Loss : 0.0553  Test Loss : 0.0389  Accuracy : 0.9956
Epoch : 308  Train Loss : 0.0642  Test Loss : 0.0387  Accuracy : 0.9956
Epoch : 310  Train Loss : 0.0681  Test Loss : 0.0383  Accuracy : 0.9967
Epoch : 312  Train Loss : 0.0635  Test Loss : 0.0381  Accuracy : 0.9967
Epoch : 314  Train Loss : 0.0674  Test Loss : 0.0380  Accuracy : 0.9967
Epoch : 316  Train Loss : 0.0559  Test Loss : 0.0380  Accuracy : 0.9967
Epoch : 318  Train Loss : 0.0600  Test Loss : 0.0379  Accuracy : 0.9967
Epoch : 320  Train Loss : 0.0569  Test Loss : 0.0376  Accuracy : 0.9967
Epoch : 322  Train Loss : 0.0608  Test Loss : 0.0374  Accuracy : 0.9967
Epoch : 324  Train Loss : 0.0579  Test Loss : 0.0372  Accuracy : 0.9961
Epoch : 326  Train Loss : 0.0575  Test Loss : 0.0370  Accuracy : 0.9961
Epoch : 328  Train Loss : 0.0639  Test Loss : 0.0367  Accuracy : 0.9956
Epoch : 330  Train Loss : 0.0575  Test Loss : 0.0366  Accuracy : 0.9956
Epoch : 332  Train Loss : 0.0544  Test Loss : 0.0364  Accuracy : 0.9961
Epoch : 334  Train Loss : 0.0553  Test Loss : 0.0363  Accuracy : 0.9956
Epoch : 336  Train Loss : 0.0590  Test Loss : 0.0364  Accuracy : 0.9956
Epoch : 338  Train Loss : 0.0575  Test Loss : 0.0369  Accuracy : 0.9939
Epoch : 340  Train Loss : 0.0556  Test Loss : 0.0370  Accuracy : 0.9939
Epoch : 342  Train Loss : 0.0514  Test Loss : 0.0367  Accuracy : 0.9933
Epoch : 344  Train Loss : 0.0489  Test Loss : 0.0362  Accuracy : 0.9939
Epoch : 346  Train Loss : 0.0508  Test Loss : 0.0357  Accuracy : 0.9939
Epoch : 348  Train Loss : 0.0549  Test Loss : 0.0353  Accuracy : 0.9961
Epoch : 350  Train Loss : 0.0565  Test Loss : 0.0349  Accuracy : 0.9967
Epoch : 352  Train Loss : 0.0565  Test Loss : 0.0346  Accuracy : 0.9967
Epoch : 354  Train Loss : 0.0541  Test Loss : 0.0345  Accuracy : 0.9967
Epoch : 356  Train Loss : 0.0596  Test Loss : 0.0343  Accuracy : 0.9961
Epoch : 358  Train Loss : 0.0534  Test Loss : 0.0342  Accuracy : 0.9961
Epoch : 360  Train Loss : 0.0509  Test Loss : 0.0341  Accuracy : 0.9961
Epoch : 362  Train Loss : 0.0449  Test Loss : 0.0338  Accuracy : 0.9961
Epoch : 364  Train Loss : 0.0564  Test Loss : 0.0334  Accuracy : 0.9961
Epoch : 366  Train Loss : 0.0582  Test Loss : 0.0332  Accuracy : 0.9967
Epoch : 368  Train Loss : 0.0599  Test Loss : 0.0331  Accuracy : 0.9967
Epoch : 370  Train Loss : 0.0567  Test Loss : 0.0330  Accuracy : 0.9967
Epoch : 372  Train Loss : 0.0571  Test Loss : 0.0332  Accuracy : 0.9967
Epoch : 374  Train Loss : 0.0602  Test Loss : 0.0334  Accuracy : 0.9967
Epoch : 376  Train Loss : 0.0549  Test Loss : 0.0332  Accuracy : 0.9967
Epoch : 378  Train Loss : 0.0517  Test Loss : 0.0330  Accuracy : 0.9967
Epoch : 380  Train Loss : 0.0539  Test Loss : 0.0329  Accuracy : 0.9967
Epoch : 382  Train Loss : 0.0535  Test Loss : 0.0327  Accuracy : 0.9967
Epoch : 384  Train Loss : 0.0552  Test Loss : 0.0326  Accuracy : 0.9967
Epoch : 386  Train Loss : 0.0600  Test Loss : 0.0327  Accuracy : 0.9956
Epoch : 388  Train Loss : 0.0573  Test Loss : 0.0328  Accuracy : 0.9956
Epoch : 390  Train Loss : 0.0586  Test Loss : 0.0329  Accuracy : 0.9956
Epoch : 392  Train Loss : 0.0524  Test Loss : 0.0329  Accuracy : 0.9967
Epoch : 394  Train Loss : 0.0521  Test Loss : 0.0329  Accuracy : 0.9967
Epoch : 396  Train Loss : 0.0575  Test Loss : 0.0327  Accuracy : 0.9967
Epoch : 398  Train Loss : 0.0501  Test Loss : 0.0324  Accuracy : 0.9967
Epoch : 400  Train Loss : 0.0488  Test Loss : 0.0322  Accuracy : 0.9967
Epoch : 402  Train Loss : 0.0584  Test Loss : 0.0322  Accuracy : 0.9967
Epoch : 404  Train Loss : 0.0506  Test Loss : 0.0321  Accuracy : 0.9967
Epoch : 406  Train Loss : 0.0447  Test Loss : 0.0321  Accuracy : 0.9967
Epoch : 408  Train Loss : 0.0494  Test Loss : 0.0321  Accuracy : 0.9967
Epoch : 410  Train Loss : 0.0516  Test Loss : 0.0321  Accuracy : 0.9967
Epoch : 412  Train Loss : 0.0477  Test Loss : 0.0319  Accuracy : 0.9967
Epoch : 414  Train Loss : 0.0488  Test Loss : 0.0318  Accuracy : 0.9967
Epoch : 416  Train Loss : 0.0478  Test Loss : 0.0317  Accuracy : 0.9967
Epoch : 418  Train Loss : 0.0497  Test Loss : 0.0316  Accuracy : 0.9956
Epoch : 420  Train Loss : 0.0479  Test Loss : 0.0313  Accuracy : 0.9956
Epoch : 422  Train Loss : 0.0534  Test Loss : 0.0310  Accuracy : 0.9967
Epoch : 424  Train Loss : 0.0601  Test Loss : 0.0307  Accuracy : 0.9967
Epoch : 426  Train Loss : 0.0463  Test Loss : 0.0305  Accuracy : 0.9967
Epoch : 428  Train Loss : 0.0498  Test Loss : 0.0304  Accuracy : 0.9967
Epoch : 430  Train Loss : 0.0512  Test Loss : 0.0303  Accuracy : 0.9967
Epoch : 432  Train Loss : 0.0486  Test Loss : 0.0300  Accuracy : 0.9967
Epoch : 434  Train Loss : 0.0505  Test Loss : 0.0296  Accuracy : 0.9967
Epoch : 436  Train Loss : 0.0479  Test Loss : 0.0293  Accuracy : 0.9967
Epoch : 438  Train Loss : 0.0521  Test Loss : 0.0292  Accuracy : 0.9967
Epoch : 440  Train Loss : 0.0511  Test Loss : 0.0294  Accuracy : 0.9967
Epoch : 442  Train Loss : 0.0515  Test Loss : 0.0297  Accuracy : 0.9967
Epoch : 444  Train Loss : 0.0416  Test Loss : 0.0299  Accuracy : 0.9961
Epoch : 446  Train Loss : 0.0474  Test Loss : 0.0302  Accuracy : 0.9961
Epoch : 448  Train Loss : 0.0490  Test Loss : 0.0304  Accuracy : 0.9961
Epoch : 450  Train Loss : 0.0514  Test Loss : 0.0304  Accuracy : 0.9967
Epoch : 452  Train Loss : 0.0472  Test Loss : 0.0304  Accuracy : 0.9961
Epoch : 454  Train Loss : 0.0480  Test Loss : 0.0303  Accuracy : 0.9956
Epoch : 456  Train Loss : 0.0510  Test Loss : 0.0300  Accuracy : 0.9961
Epoch : 458  Train Loss : 0.0487  Test Loss : 0.0297  Accuracy : 0.9967
Epoch : 460  Train Loss : 0.0467  Test Loss : 0.0296  Accuracy : 0.9967
Epoch : 462  Train Loss : 0.0502  Test Loss : 0.0295  Accuracy : 0.9967
Epoch : 464  Train Loss : 0.0488  Test Loss : 0.0292  Accuracy : 0.9967
Epoch : 466  Train Loss : 0.0451  Test Loss : 0.0289  Accuracy : 0.9967
Epoch : 468  Train Loss : 0.0506  Test Loss : 0.0287  Accuracy : 0.9967
Epoch : 470  Train Loss : 0.0452  Test Loss : 0.0287  Accuracy : 0.9967
Epoch : 472  Train Loss : 0.0462  Test Loss : 0.0289  Accuracy : 0.9967
Epoch : 474  Train Loss : 0.0404  Test Loss : 0.0290  Accuracy : 0.9961
Epoch : 476  Train Loss : 0.0487  Test Loss : 0.0290  Accuracy : 0.9956
Epoch : 478  Train Loss : 0.0447  Test Loss : 0.0288  Accuracy : 0.9956
Epoch : 480  Train Loss : 0.0513  Test Loss : 0.0284  Accuracy : 0.9956
Epoch : 482  Train Loss : 0.0396  Test Loss : 0.0281  Accuracy : 0.9956
Epoch : 484  Train Loss : 0.0411  Test Loss : 0.0278  Accuracy : 0.9961
Epoch : 486  Train Loss : 0.0416  Test Loss : 0.0274  Accuracy : 0.9967
Epoch : 488  Train Loss : 0.0461  Test Loss : 0.0272  Accuracy : 0.9967
Epoch : 490  Train Loss : 0.0465  Test Loss : 0.0272  Accuracy : 0.9967
Epoch : 492  Train Loss : 0.0419  Test Loss : 0.0271  Accuracy : 0.9972
Epoch : 494  Train Loss : 0.0396  Test Loss : 0.0271  Accuracy : 0.9972
Epoch : 496  Train Loss : 0.0478  Test Loss : 0.0271  Accuracy : 0.9967
Epoch : 498  Train Loss : 0.0437  Test Loss : 0.0273  Accuracy : 0.9956

In [126]:
torch.save(m5.state_dict(), "saved_models/m5.pth")